### ISSUE TITLE
Plot collapses after changing plot options

### ISSUE THREAD

**Issue by prs513rosewood** [ContactEngineering/topobank#1001]
In plot options, selecting "Optimize plot for print", then selecting "Optimize plot for web" causes the plot's y axis to collapse.

![image](https://github.com/ContactEngineering/topobank/assets/328212/182a1b09-c12f-48b9-8d1d-d8f4c8bcbefc)

**Comment by pastewka** [comment]
Thanks for reporting @prs513rosewood . Will check what is going on.
