### ISSUE TITLE
.gwy file not uploading

### ISSUE THREAD

**Issue by ArushiPradhan** [ContactEngineering/topobank#1007]
Hello,
I tried to upload a .gwy file but it did not work.

**Comment by pastewka** [comment]
Hi @ArushiPradhan , I see that there is a problem. Can you send me the specific file that caused the error by makl (and indicate whether I can include it in our public repository for testing).

**Comment by pastewka** [comment]
Hi @ArushiPradhan - can you check whether this problem has been resolved? I have made fixes to the GWY reader.
