### ISSUE TITLE
Unable to download image from a shared surface

### ISSUE THREAD

**Issue by Vchadha2** [ContactEngineering/topobank#1009]
https://contact.engineering/manager/html/topography/6404/
This surface was shared with me, but I am unable to download a PNG file of a optical profilometer from it.

**Comment by Vchadha2** [comment]
Well I downloaded and uploaded .zon file on a new surface to be able to download the plot, I could not, I think that feature has a bug

**Comment by pastewka** [comment]
Hi @Vchadha2 - thanks for reporting, I'll check what is going on. I see an error that was generated automatically by the system.

**Comment by pastewka** [comment]
Fixed by [551c85a](https://github.com/ContactEngineering/topobank/commit/551c85a1260ae924043f909711209d484e0aca3c)
