### ISSUE TITLE
Downloading Bokeh plots does not download the SVG but displays it in the browser

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/topobank#1011]
The SVG should download, not display.

**Comment by pastewka** [comment]
Hi @ArushiPradhan and @Vchadha2 - we are trying to reproduce the issue with the Bokeh downloads. You mentioned that they show in the browser rather than downloading. We just tired to reproduce the issue but could not.

Can you tell us where you saw the issue, i.e. what were you trying to do on the site and which browser did you use?

**Comment by ArushiPradhan** [comment]
Hi,
I clicked the download icon next to the figure of the PSD. When we open the downloaded file it shows up in the browser. I have attached the downloaded file and here's the screenshot:
[cid:1b4b0531-a587-4bdb-9b85-7634c9a8dc69]
Thank you,
Arushi
________________________________

**Comment by ArushiPradhan** [comment]
Hi,
I just realized I can choose "open with" and change the program to open the .svg file to prevent it from opening in browser. Sorry about that!

Thank you,
Arushi

________________________________

**Comment by pastewka** [comment]
I never changed any settings here. On my computer it just downloads. Can you send the screenshot again, it does not show here.

**Comment by pastewka** [comment]
Hi @ArushiPradhan @SickSmile1 - just FYI, it's fixed in the code base but that code base is not yet deployed (so @ArushiPradhan will not be able to check whether it is working). Will notify here once the thing is online, but I will need to fold some other (big) changes into the code first.

**Comment by pastewka** [comment]
Fixed with #1022
