### ISSUE TITLE
Error in PSD download 

### ISSUE THREAD

**Issue by akp107** [ContactEngineering/topobank#1019]
We get an error message (page not found) when downloading the PSD in any format. For all PSD

**Comment by pastewka** [comment]
I will check what is going on. Thanks for reporting!

**Comment by pastewka** [comment]
@akp107 I've justed pushed an update that should fix the download. Can you confirm that it is working again?

**Comment by akp107** [comment]
Yes, now this work. Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
