### ISSUE TITLE
Unable to download any analysis 

### ISSUE THREAD

**Issue by ArushiPradhan** [ContactEngineering/topobank#1020]
Hi,
Trying to download any of the analyses leads to an error page. 

Thank you!

**Comment by pastewka** [comment]
Duplicat of #1019

**Comment by pastewka** [comment]
@ArushiPradhan I've just pushed an update that should fix the download. Can you confirm that it is working again?

**Comment by ArushiPradhan** [comment]
It us working for roughness parameters but not PSDs.
________________________________

**Comment by pastewka** [comment]
Can you hold the Shift-Button down while reloading the page? I think your browser may be caching old JavaScript Code.

**Comment by ArushiPradhan** [comment]
Issue is fixed now! thank you,
Arushi

________________________________

**Comment by pastewka** [comment]
Okay, perfect!
