### ISSUE TITLE
physical size of file shows 0

### ISSUE THREAD

**Issue by ArushiPradhan** [ContactEngineering/topobank#1039]
physical size of file is showing 0
Please see screenshot
![Screenshot from 2023-11-15 19-05-46](https://github.com/ContactEngineering/topobank/assets/78487900/b174e36f-8b52-406c-8897-9a6ce45e1502)

**Comment by pastewka** [comment]
Hi @ArushiPradhan - can you share that data file with me?

**Comment by pastewka** [comment]
Also resolved
