### ISSUE TITLE
Duplicate properties (key-value pairs)

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/topobank#1105]
**Describe the bug**
The API allows creation of a property that already exists. This property will the exist twice in the database.

**Expected behavior**
Property/surface pairs should be unique. Creation (POST) of a new property with the a name that already exist should update that existing property.

**Comment by pastewka** [comment]
@IoannisNezis - I am currently running into an issue where duplicate properties are created.

Is it reasonable behavior to update a property on POST if it already exist or is it better to throw an error? I am ambivalent about this. From a frontend perspective, the error may be simpler.

**Comment by pastewka** [comment]
It may be useful to rethink the API design and eliminate the dedicated property API/view set altogether.

We could simply update and return properties as an object in the `Surface` model:

```js
{..., properties: {
    friction: {value: 1.0, unit: ''},
    adhesion: {value: 2.0, unit: 'N'}
}
```

**Comment by IoannisNezis** [comment]
Hey @pastewka that"s true, properties the serializer currently allows non unique property names for the same surface.
The UI prohibits this by invalidating the form.
May i ask how you noticed this issue?

I would simply throw a validation error from the serializer at POST,
that would cost a db lookup.

Redesigning the API may be a good idea,
i would like to read up a bit on good api design, currently i don"t really have a option on this.

But i would prefer to treat those issues separately, as this will keep things simpler.
I'll open a PR for this issue, where i add uniqueness as a validation step in the Property-serializer and 
add the API redisign idea to the List in the OpenApi PR (that i'll open in the future as well).

**Comment by pastewka** [comment]
I agree that API redesign should be a a separate issue. I am also unsure about folding this into a dictionary property as suggested above by me, as this would allow overwriting *all* properties with a single API call (and hence bugs in the frontend may delete properties).

I'll start a separate issue on general REST API design questions.
