### ISSUE TITLE
Remove dependency on `django-tagulous`

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/topobank#1111]
**Describe the maintenance task**
We are using `django-tagulous` for tags in `Surface` and `Topography`. It should be easy to replace this functionality with a custom tag model.

**Describe why this task is necessary**
`django-tagulous` appears to be no longer maintained: https://github.com/radiac/django-tagulous/issues/178

**Additional context**

**Comment by pastewka** [comment]
An alternative may be forking and maintaining ourselves. The project is not super complex.

**Comment by radiac** [comment]
In case it helps, I've just pushed tagulous v2.0 to pypi, supporting Django 3.2 to 5.1 and hopefully addressing all outstanding issues. It wasn't abandoned, I've just been busy!

**Comment by pastewka** [comment]
Will keep depedency on tagulous for now.
