### ISSUE TITLE
Insert legend in output when saving analysis plots as images

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#114]
Currently, the plots have no legend inside the plot. The user sees the checkboxes
below the plot. When saving as image file, these checkboxes are no longer there
and the image is missing a description of the meaning of the lines.

**Comment by pastewka** [comment]
I think this should be resolved in the current version, since you can turn the legend on and off.

**Comment by mcrot** [comment]
Yes, this works now. Closing.
