### ISSUE TITLE
Show distribution of absolute gradient as extra tab in slope distributions

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#117]
Find a way to specify result card template and multiple plots in result, e.g. by adding extra layer for tabs in result dict (+option for template).

**Comment by mcrot** [comment]
Is the display of the absolute gradient still relevant for the slope distribution, @pastewka ?
I seem to recall that it's not.

**Comment by pastewka** [comment]
This also seems to be superseded by #844
