### ISSUE TITLE
Show data points as symbols if number of data points is low

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/topobank#135]
If it is clear that the plot is a linear interpolation between data points, we should show these data points with symbols. This does no longer make sense if the number of data points is large. The plot view should automatically turn symbols on and off.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/2530391/53909966-15941400-4053-11e9-9c98-ece7a9e29b95.png">

**Comment by mcrot** [comment]
> 
>   * There is an inconsistency in displaying x-y profiles. Sometimes it
>     shows the data points, sometimes it does not.
>       o Compare attached /Screenshot_Points.png/ with
>         /Screenshot_NoPoints.png/
>       o Why the discrepancy?
>       o (Not sure that it really matters, but it's a bit odd)
> 
> Sounds like a bug. We need to fix this.
Actually, that's not a bug, but a feature and was implemented because of this issue.

So the question is: What do we want?

**Comment by pastewka** [comment]
Of course, I remember. I think we should leave as is.

@tdbjacobs What is you opinion on this?

**Comment by tdbjacobs** [comment]
I thought the two profiles I showed in the screenshots (one with points and
one without) had approximately the same number of points.

However, it must be the case that one of them was a little over and the
other was a little under.

OK to leave as is.

-Tevis





Tevis Jacobs
William Kepler Whiteford Faculty Fellow and Associate Professor
Mechanical Engineering and Materials Science
University of Pittsburgh
http://www.engineering.pitt.edu/JacobsLab/
Mail: 636 Benedum Hall, 3700 O'Hara St., Pittsburgh, PA 15261
Office: 538-E Benedum Hall, 412-624-9736
tjacobs@pitt.edu
