### ISSUE TITLE
Fork implementation of optional terms to IMTEK organization on github

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#159]
For implementing #73 , an new repo was created in order to extend an existing package:

 https://github.com/mcrot/django-termsandconditions/tree/optional_terms

The implementation is still in the branch `optional_terms` and will be installed when
the requirements for topobank are installed. For future development it's maybe better to
also fork this to the organizational github account and to use the package from there.

**Comment by pastewka** [comment]
I this still an issue @mcrot ? I thought you are using the default package now

**Comment by mcrot** [comment]
Yes, that's correct, I'm using now the official one.
