### ISSUE TITLE
Remove references to sb-admin template

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank#169]
Initially, the sb-admin template was used for the website, but most of it was removed later.
There are still some files used in the code of the base template:
```
<!-- CSS from sb-admin-2-bs4 template -->
<link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">
[...]
script src="{% static 'js/sb-admin.js' %}">
```

It cannot be removed right now, because it looks less nice, but I think there
are only small benefits from these imports which can be realized by only a few lines of JS/CSS code instead.

**Comment by pastewka** [comment]
Closed by #965
