### ISSUE TITLE
Check exception handling on unit conversion errors while plotting

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#170]
See TODO here: https://github.com/pastewka/TopoBank/blob/3d1ef2a15811196f37266fc0895c3f4b31686aef/topobank/analysis/cards.py#L136

**Comment by pastewka** [comment]
Does this ever happen?

**Comment by mcrot** [comment]
I haven't found this so far. I'll remove the TODO and reraise if this happens. Probably it will only happen if we'd ever use some units which the package `pint` does not support.

**Comment by mcrot** [comment]
The code is not included any more, this is now handled by displaying a warning in the UI. Closing.
