### ISSUE TITLE
Recommendation for citations

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank#171]
Currently in text files, there is only a stub:
```
# Height Distribution
# ===================
# TopoBank version: 0.1
# PyCo version: 0.31.0
# IF YOU USE THIS DATA IN A PUBLICATION, PLEASE CITE XXX.
[...]
```

**Comment by mcrot** [comment]
We could use decorators here.

**Comment by pastewka** [comment]
We now have a mechanism for this in `SurfaceTopography` and need to use it in `ContactMechanics`

**Comment by pastewka** [comment]
`ContactMechanics` now also reports citations

**Comment by pastewka** [comment]
This is not just downloaded data but could also be shown on the web page.

**Comment by mcrot** [comment]
I've implemented the output of the DOIs into the analysis results (txt, xlsx).
I've added a menu item here:
![grafik](https://user-images.githubusercontent.com/9113541/212723072-a096c1e9-571b-4372-a887-b22619946a84.png)
which opens a modal window:
![grafik](https://user-images.githubusercontent.com/9113541/212723199-e6957a81-6350-4564-ab41-4069c829d6e9.png)
Clicking on a DOI opens a new tab showing the corresponding article.

**Comment by pastewka** [comment]
Okay fantastic. It would be good if this could be resolved to an actual citation. I think a static dictionary doi->text or html would suffice for that.

**Comment by mcrot** [comment]
Is the citation needed in the download files also or only in the UI?
In the downloads it would take quite some space and it might look a bit cluttered.

**Comment by pastewka** [comment]
I think it would be good in both places. I know which paper this is from the full citation, but not from the DOI. The DOI should still be there of course...

**Comment by mcrot** [comment]
Okay, fine. What do you think of using a service like https://citation.crosscite.org/ in the background and saving the results in the database? These entries could also be edited manually in the admin interface.

I'm a bit worried that maintaining the static dictionary will become tedious, e.g. consider this case:
A plugin uses a new analysis function which results in a new DOI, but the static dictionary hasn't got this DOI yet. 
So a new version of a plugin would also enforce a new version of the main application.

**Comment by pastewka** [comment]
If this works automatically through crosscite, fantastic! I just thought a static dictionary would be easier.
