### ISSUE TITLE
Use labels with different colors to distinguish surfaces and topographies

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#175]
Just an idea:

Currently, in the input fields for topography or surface selection, it is difficult
to distinguish what is a topography or a surface. Maybe we can use different colors
for the labels - and maybe use these colors everywhere in order to indicate whether
it is a surface or a topography.

**Comment by mcrot** [comment]
Probably handled by #775.

**Comment by pastewka** [comment]
This has been addressed in #775
