### ISSUE TITLE
Show profile as an interactive 3D plot

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#182]
https://www.profilmonline.com/ has the ability to show interactive 3D plots,
which can be rotated. This would also be nice for TopoBank.
A simple implementation could be maybe done with http://visjs.org/graph3d_examples.html (if it's okay to transfer all data to client). Maybe (Dash)[https://plot.ly/products/dash/] is also interesting, they also support 3D visualizations: https://dash-gallery.plotly.host/dash-yield-curve/

**Comment by pastewka** [comment]
Related to #679

**Comment by pastewka** [comment]
I am closing this as we are now moving to Openseadragon
