### ISSUE TITLE
Some files take too much time during topography creation

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#215]
Some files, like the one uploaded in #212 (https://github.com/pastewka/TopoBank/files/3248901/mcd_2.5um_512px_stiched_3x.txt.zip, unzip, than upload), take too much time to be processed. The upload is quite fast, but every further step takes long. 

Maybe this can be solved by using the new reader structure from Pyco, I don't know yet what causes this. In the meanwhile, I had to increase timeouts for `gunicorn` as workaround (#212).

**Comment by pastewka** [comment]
Is this still an issue?

**Comment by mcrot** [comment]
I don't think so. After uploading it's okay. Closing.
