### ISSUE TITLE
Delete uploaded files from wizard if uploading fails

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank#223]
If uploading fails, some files could be left in the temporary directory of the 
wizard view which creates the topography. I'm not sure how often this happens, but it's safer to delete old files as advised [here](https://django-formtools.readthedocs.io/en/latest/wizard.html).

**Comment by pastewka** [comment]
Should be fixed with #173

**Comment by pastewka** [comment]
Resolved with #1012
