### ISSUE TITLE
Unknown-format error message unclear

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/TopoBank#247]
Opened by @tdbjacobs

For unknown file type, would be better if message was clearer to user. 

<img width="1680" alt="Screen Shot 2019-07-09 at 7 26 09 PM" src="https://user-images.githubusercontent.com/22891610/60930042-cfa9bf80-a281-11e9-9149-79a6338b8754.png">

**Comment by mazharrazmian** [comment]
Is this already fixed? Because this is the error message I get when a wrong file format is uploaded:
![image](https://user-images.githubusercontent.com/42150817/179970374-31e2612d-de31-4298-a882-7cf49110c032.png)

**Comment by mcrot** [comment]
Yes, I think this as been fixed, thanks. Closing.
