### ISSUE TITLE
Seems intuitive that there would be a "share new topography" on the Sharing page

### ISSUE THREAD

**Issue by tdbjacobs** [ContactEngineering/topobank#270]
When I click on the Sharing page, it gives me an overview of all data that I am sharing or are shared with me. This is great. 

However, I would also expect to see a "Share new Surface" button on this page. (I now know that you can go to the surface and click share. But when I was new to the app, I clicked to the Sharing page and it wasn't immediately obvious how to start sharing topographies

**Comment by pastewka** [comment]
This has been completely revised. That user interface no longer exists.
