### ISSUE TITLE
Provide favicon

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank#293]
Currently the browser always gets a 404 on request of `/favicon.ico`. What can we use here?

**Comment by mcrot** [comment]
Yes, this is the small icon shown in tab header in the browser.

It's still the only web app I use without icon. So I've just had the idea to try out a picture of your publication:
![grafik](https://user-images.githubusercontent.com/9113541/95595375-600a1d80-0a4c-11eb-9e68-175d66cc3664.png)

And here it is in the tab header:

![grafik](https://user-images.githubusercontent.com/9113541/95596744-11f61980-0a4e-11eb-8c8d-690ac3cbce74.png)


A simple, vectorized logo would be probably better, but it's not easy to have a general icon, because topographies exist on so many scales and there are multiple methods to measure them. Maybe also a job for an agency?

@pastewka , what do you think about using such a plot?

PS: And the browser tab should show "contact.engineering" instead of "TopoBank".

**Comment by pastewka** [comment]
I am reopening this. The favicon is still the old one.

**Comment by pastewka** [comment]
Actually looks good on my current browser.
