### ISSUE TITLE
HDF5 upload does not work

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/topobank#302]
When trying to upload the contact mechanics challenge surface in HDF5 format (see https://www.lmp.uni-saarland.de/index.php/surface-configurations-for-contact-challenge/) I get the below error. PyCo supports this format.

![grafik](https://user-images.githubusercontent.com/2530391/61459980-d9938880-a93b-11e9-9937-a3ef73222d56.png)

**Comment by sitangshugk95** [comment]
Is the file for the contact mechanics challenge (with the proper rotation/scaling) uploaded somewhere as a published data on contact.engineering?
