### ISSUE TITLE
Unit conversion issue in OPD files

### ISSUE THREAD

**Issue by tdbjacobs** [ContactEngineering/TopoBank#324]
I uploaded a new OPD file (which I had not uploaded previously). And it is having a very strange z-height issue.

When it auto-detects the z-height and units, then it shows a scale bar that goes up to 10^34 m, but the whole surface appear purple (lowest height). See screenshots.

One screenshot shows image as rendered by optical profilomter software (scale is in nm, but values are in the 10,000 range (so should be microns)). 
The other screenshot shows the same data as rendered by webapp (scale in mm, goes up to 10^34)

<img width="541" alt="Screen Shot 2019-07-23 at 10 48 53 AM" src="https://user-images.githubusercontent.com/22891610/61722203-dc292000-ad37-11e9-8f43-c87204dc863f.png">
<img width="1139" alt="Screen Shot 2019-07-23 at 10 49 06 AM" src="https://user-images.githubusercontent.com/22891610/61722205-dc292000-ad37-11e9-9527-6045bde823a1.png">

**Comment by pastewka** [comment]
@tdbjacobs @abg30 - can we resolve this issue?
