### ISSUE TITLE
Remove topography fields named "*_editable"

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank#342]
Probably they are no more needed because the readers in PyCo>=0.51.1 support
testing for dimensions, height_scale_factor, unit and sizes.

**Comment by pastewka** [comment]
Is this still an issue?

**Comment by mcrot** [comment]
Yes.

**Comment by pastewka** [comment]
Still this information needs to be cached. We don't want to open the file each time a user requests information on a specific measurement.

**Comment by pastewka** [comment]
We may want to indicate clearly which fields are cached from the file and refresh the case when the sequeezed file is renewed.

**Comment by pastewka** [comment]
I think those fields are needed. The code does not clearly indicate which properties are cached from the file, but I am not sure this is necessary.
