### ISSUE TITLE
BUG: y-label in curvature distributions should be probability density and not Probabilty

### ISSUE THREAD

**Issue by sannant** [ContactEngineering/TopoBank#350]
![grafik](https://user-images.githubusercontent.com/40853209/64096177-3cf93e80-cd61-11e9-9e2f-27f9a0c4df7c.png)
units are fine

**Comment by mcrot** [comment]
@pastewka I could easily change this is in the current develop branch (`functions.py`) and trigger a recalculation
of all height/slope/curvature distributions. Or does it make more sense to do this in #775 , because analyses have to be triggered there anyway? Then I would shift this to 0.19.0.
