### ISSUE TITLE
Possible inconsistency when unsharing surfaces

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank#359]
Currently the following scenario can happen:

1. User A creates a surface and shares it with user B. B is allowed to change it.
2. User B creates a topography and uploads his own data in order to collaborate.
3. User A "unshares" the surface and user B can no longer use it.
4. User A can still use the topography data of user B.

This seems to be wrong. Possible solutions are:
- the topography uploaded by B is removed from the surface when unsharing
  (ineffective, because user A can download it beforehand)
- the share cannot be taken from B because he/she has shared data

Here are some quirks - we should rethink the sharing and uploading.

**Comment by pastewka** [comment]
I don’t think there is a solution to this. if you upload data to someone elses surface twin, you are transfering that data. Note that we can now transfer ownership.
