### ISSUE TITLE
Filename for saving plot image

### ISSUE THREAD

**Issue by lthimons** [ContactEngineering/topobank#364]
When saving a plot from analysis (using the save icon next to the plot) the filename is automatically set to "bokeh_plot". It would be nice to save them with a more descriptive name such as PSD plot, or height distribution, etc. like the text files are saved as.

**Comment by pastewka** [comment]
In addition, some browser show the file in the browser but it should download into a file.

**Comment by SickSmile1** [comment]
> In addition, some browser show the file in the browser but it should download into a file.

Is this resolved? if not, please name the Browser(mobile?). Still could not replicate the behaviour.

**Comment by pastewka** [comment]
I could never reproduce the issue with the file showing in the browser, but the file name issue remains I think.

**Comment by pastewka** [comment]
In line 307 of `BokehPlot.vue`, try passing a `filename` parameter to the `SaveTool` constructor, e.g.

```javascript
const saveTool = new SaveTool({filename: 'abc.svg'});
```
