### ISSUE TITLE
Scale dependent slope

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#403]
New analyses "scale dependent height/slope/curvature"

**Comment by pastewka** [comment]
The scale dependent slope is simply the square root of the ACF divided by the distance

**Comment by mcrot** [comment]
Thanks for the PR! If it's okay that we keep the unit "1" for slopes, that I can also so the changes on the PR.

**Comment by pastewka** [comment]
Closed with #611
