### ISSUE TITLE
Analysis fails for 8k by 8k surface...

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/topobank#410]
...and possibly larger. I uploaded the 8k HDF5 from the contact mechanics challenge. The PSD analysis fails with a memory error, the other analyses just stall. We should either limit the topography size or make this work (the latter preferred). This may require moving the Computational part to a separate server.

**Comment by pastewka** [comment]
I need to check that this has been resolved

**Comment by pastewka** [comment]
This still seems to be an issue. There is also no easy way to retriggered a failed calculation.

**Comment by mcrot** [comment]
Yes, once there was a trigger button (#318 ), I would also like to have something like this again.
For the user, but also in an admin panel with overview over all analyses and filters for their states (running/pending/started/failure).

Hm - we are already on a larger server. Is it still a memory error?

**Comment by pastewka** [comment]
It complains about a redis connection loss. My guess is the process is killed because of memory issues.

**Comment by pastewka** [comment]
We now have a trigger button again for all analyses and for cache renewal.

**Comment by pastewka** [comment]
This is still an issue. DZI creation works but analysis fails with an error message that is not particularly explanatory:

![image](https://github.com/ContactEngineering/topobank/assets/2530391/eb085a70-fa58-47cf-9b51-a755e2a2a612)

**Comment by pastewka** [comment]
This is not because of memory issues, but Redis limits. Disable caches fixes this. Putting the whole topography data into the cache does not make sense, it is bound to be slow as it's pickled.
