### ISSUE TITLE
Are resolution_x and resolution_y needed in database?

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank#425]
So far, the resolution is displayed only in the topography details
but not used in any other template or calculation.

Since the PyCo topography is evaluated in the topography details because
of the image plot, the resolution could be gathered quite easy at that point.
On the other hand, it is a bit extra effort to save the resolution
during the upload. Maybe we can remove it from there?!

**Comment by pastewka** [comment]
I think we should keep it in the database. Some of this information needs to be cached to avoid opening the file to obtain it.
