### ISSUE TITLE
Saved analysis results depend on pickle version

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#426]
Currently the analysis results depend on the pickle version. Is pickle
guaranteed to be downward-compatible, so that newer versions can always read
older pickled objects?

Or do we need some special procedure here if there is a new pickle protocol?

**Comment by pastewka** [comment]
Is this still an issue? I thought everything is now JSONified...

**Comment by mcrot** [comment]
No, this is still a BinaryField, the instrument parameters are JSON.

We could also convert this to JSON, but we need to take care of two things:
1. Pickle can encode numpy arrays, in JSON we would need to encode this to lists. This might be larger (array can be compressed) and extra overhead is needed for rebuilding the array each time the result is used. We should do some experiments before replacing pickle here.
2. We have to find a representation for exceptions which are currently pickled in case of analysis failures.

**Comment by pastewka** [comment]
Don't worry, I thought this was simple

**Comment by pastewka** [comment]
Analysis results are no longer stored in the database but as JSON in the S3. However, analysis parameters are still pickled. We should open a separate issue for this if we think this is a problem.
