### ISSUE TITLE
Prepopulate date of measurement with `acquisition_time` if present

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/TopoBank#433]
The info dictionary may have an `acquisition_time` entry. (This currently only works for DI files.) If present, this should be used for the date of the measurement.

**Comment by mcrot** [comment]
Should the measurement date be nullable, i.e. optional in the user interface?
So, if no measurement date is given in the file, it should be possible to leave it empty?

**Comment by pastewka** [comment]
Not sure. We had decided in the past that we would force the user to provide a measurement date.

@tdbjacobs What's your opinion on this.

**Comment by mcrot** [comment]
Another detail to clarify here: The file can contain multiple channels. Each channel has its own aquisition time, so it
is not unique. However, the date is probably unique. We could use the common date if it's the same for all aquistions and otherwise leave the field empty.

**Comment by pastewka** [comment]
Ahhh... what a mess

**Comment by tdbjacobs** [comment]
Oy.

I would probably just anticipate that all of the dates would be the same,
and so then the choice doesn't matter so much.

(Then I would use some simple rule: such as the value from the first
channel reported, or use the earliest date, or the latest date).




Tevis Jacobs
William Kepler Whiteford Faculty Fellow and Associate Professor
Mechanical Engineering and Materials Science
University of Pittsburgh
http://www.engineering.pitt.edu/JacobsLab/
Mail: 636 Benedum Hall, 3700 O'Hara St., Pittsburgh, PA 15261
Office: 538-E Benedum Hall, 412-624-9736
***@***.***

**Comment by mcrot** [comment]
Ok, thanks. I will use a simple rule like taking the latest date available on all channels, if any.
Should be fine in most cases.

**Comment by pastewka** [comment]
I agree, let's just use the latest date.
