### ISSUE TITLE
I think we should replace "Mean height" with "Average Height Deviation"

### ISSUE THREAD

**Issue by tdbjacobs** [ContactEngineering/TopoBank#449]
In the "Special Values", we report "RMS height" and also "Mean height". I don't think this makes sense because the mean height is normally equal to zero (or, e.g., -6e-18) since most surfaces are mean-subtracted upon entering them. 

Perhaps we should report the Average Height Deviation instead, which is <|h-h_mean|>.

NOTE: In terms of nomenclature, the RMS height is similar to "Rq" and the Average Height Deviation is similar to "Ra" - but we cannot call them Rq and Ra because, to compute those, you typically do gaussian filtering ahead of time (per ISO and ASTM standards)

-Tevis

**Comment by pastewka** [comment]
Not all standards gave that filter.

**Comment by mcrot** [comment]
In the current version, the tab "special values" does not longer exist. All these values are reported under "Roughness parameters". Here there is only "RMS Height" (Rq) is reported, no "Mean height" any more.
Is this still an issue?
