### ISSUE TITLE
Reappearing basket item after closing

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank#482]
On the "Analyze" tab, while there analyses are still loading, clicking on the
"close" symbol on a basket item has no effect: The page is reloaded and the 
basket item is still there.

One would expect that the basket item is removed from basket and all
analyses related to the item are not loaded any more.

**Comment by mcrot** [comment]
This seems to happen not only when still loading, but also when not only one 
but two analyses functions are selected, in Firefox as well as Chrome.

**Comment by mcrot** [comment]
This is difficult to reproduce. I've just tried and initially I've seen this behaviour, but later not. It seems that this only happens for new topographies or new analyses, but not sure. I'm shifting this to a later milestone in order to check again.

**Comment by mcrot** [comment]
Still difficult to reproduce. Maybe not relevant for normal use. I'm removing the milestone. Let's see if this happens again
in an annoying way.

**Comment by pastewka** [comment]
This part of the code has been largely rewritten. Closing this.
