### ISSUE TITLE
Store topographies in flexible backend

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#49]
# User Story

As provider of the web service we want to store all the topography data in order to be able to do machine learning on it or publish the data someday.

As researcher I want to collect my topography data at one place in order to (re)perform calculations on different topographies easily.

As provider we want to be able to switch the backend later in order not to be dependent on one provider (e.g. SciServer).

# Acceptance Criteria

-  a user can upload his topographies, logout, login again later and see details on already uploaded data
-  we as provider have the possiblity to use all topography data uploaded by the users
-  the backend is used via a common interface so that it could be theoretically exchanged

The first supported backend is the local filesystem. It should be possible to extend the application later by saving the data in the sciserver infrastructure (volumes).

*Should the user be able to switch backend systems? How are the files moved then?
Some more description work needed here.*

**Comment by pastewka** [comment]
I think this is out of scope now that we are starting to work with distribution of Data directly from S3 with presigned keys.
