### ISSUE TITLE
Contact Mechanics: Sometimes layout of E* line in form is broken

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#498]
Sometimes there is an extra line in the form, because of an unexpected line break in the line for pressures:
![grafik](https://user-images.githubusercontent.com/9113541/85837520-670c6900-b798-11ea-9740-89de5def0f1d.png)

**Comment by mcrot** [comment]
This seems to be timing related, probably because the plot is not fully loaded yet.
When reloading the page it looks fine. I'll remove the milestone, let's see how this behaves in production.

**Comment by mcrot** [comment]
Is this still relevant?

**Comment by pastewka** [comment]
It now looks better.
