### ISSUE TITLE
Replacing jQuery with Vuejs in analysis forms?

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank#499]
Now in the select tab almost everything is done with vuejs. When displaying the analyses 
for contact mechanics, jQuery is used to set initial values for the form and other things.
Maybe this can be made more robust using vuejs, we'll have to check.

**Comment by pastewka** [comment]
Yes, we should remove jQuery, but I think we need a proper REST API to remove the code injection which is currently handled by jQuery.

**Comment by pastewka** [comment]
Closed by #965
