### ISSUE TITLE
502 Bad Gateway when uploading nc file exported with PyCo

### ISSUE THREAD

**Issue by sannant** [ContactEngineering/topobank#502]
Maybe it is because the file has 1Gb Size

**Comment by AntoineSIMTEK** [comment]
The file name is facets_super_grain_correlated_interpolate.nc, I can send it to you directly to try out

**Comment by mcrot** [comment]
Yes, one gigabyte is quite huge. This would cause several gigabytes on extra data for contact mechanics calculation and I'm not sure, if the memory will always suffice for the calculations. Is it a file with many channels and you would only choose one channel which is significantly smaller than 1 GB?

I'm not sure yet, where the upload failed. Before I investigate further, I would like to discuss how large the maximum files/arrays should be that we want to process with TopoBank. @pastewka , @AntoineSIMTEK , is 1GB a reasonable maximum size?

**Comment by AntoineSIMTEK** [comment]
It is computer generated data. And one issue is that I cached some fields in the info dict. That might be the issue. 

The true data is "only" 1 Gb. 

It is a linescan. 

It is computer generated, probably only computer generated data can be so huge. So we don't need to support it.

**Comment by AntoineSIMTEK** [comment]
Still we should check if an nc linescan of a reasonable size exported with PyCo works.

**Comment by AntoineSIMTEK** [comment]
Since the 300mB long linescan  is already challenging my computer's RAM, O think 1Gb is enough for an upper limit.

**Comment by mcrot** [comment]
Well, I would appreciate, if the upper limit is lower than 1 GB - it's quite huge, and I think it would be easier to first ensure a lower maximum size than that.

**Comment by AntoineSIMTEK** [comment]
How many Mb is the biggest contact Mechanics Challenge surface ?

**Comment by AntoineSIMTEK** [comment]
I tested with a simple small nc linescan exported from SurfaceTopography.  It works.

**Comment by pastewka** [comment]
@AntoineSIMTEK can you check whether this works now?

**Comment by AntoineSIMTEK** [comment]
No. 

<img width="1278" alt="grafik" src="https://user-images.githubusercontent.com/40853209/147569228-24dbb366-9089-4288-9538-3d6c2eec3993.png">

**Comment by pastewka** [comment]
Is this still an issue?

**Comment by mcrot** [comment]
@sannant I don't find the original file for this issue, can you test again?

**Comment by sannant** [comment]
But the question is whether we want to fix it at all

**Comment by pastewka** [comment]
Closing this as it seems to be a non issue for practical purposes. We will also redesign file upload, see #173
