### ISSUE TITLE
Upgrade celery

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#527]
Celery 4.x.x is a long term supported release and the support ends in August 2021. Before an upgrade to a 
larger version should be made. See also #526 , maybe the Docker config has to be updated too, because
flower may be started in a different way for celery 5.x.

**Comment by pastewka** [comment]
Has celery already been updated @mcrot ?

**Comment by pastewka** [comment]
There is also #710

**Comment by mcrot** [comment]
Yes, we are using Celery version 5.2.1 now. Thanks for noticing. #710 is relevant when we switch to Celery 6.x. Closing.
