### ISSUE TITLE
Landing page proposals

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank#538]
I'm creating this issue to bundle the discussion about requested changes to the landing page.

**Comment by mcrot** [comment]
Tevis suggested to change the mission-statement sentence to a bulleted list:

> This is a web-based application that allows you to:
>  - Upload, store, and share topography measurements
>   - Collectively analyze many measurements of a single surface (even if taken at varying size scales or with different techniques)
>   - Compute contact properties, such as deformation and true contact area under loading
>   - Publish your datasets (when you are ready).

Additionally he suggests to include a sentence below "Login via ORCID" (and the ORCID button) that says "Or, you can browse published surfaces even before you login." 

Underneath two buttons :
-  "Browse all published surfaces" (takes them to the surfaces menu)
-  "Jump to one random surface" (takes them to the rotating thumbnail view of a random surface)

**Comment by mcrot** [comment]
@pastewka suggested the following:

> 
> I like the “carousel” that Michael implemented for the topographies. For the landing page, I think a carousel that just flips through random published topographies would be great. (We need a couple of published surfaces for this, but we will have those soon.) Below the figure it could show the citation and when you click on the topography it takes you the topography view. I would hide the statistics between the little “i” on the top right.
> 
>  I would keep the current text above the “carousel”, but in favor of saving screen real estate I would not turn it into bulleted list.

**Comment by mcrot** [comment]
I think @pastewka proposal would increase the appeal to check out the site. 
I also like a mission statement more than bullet points as a first contact with the site.

Btw. there is another site for topographies which shows pictures of random examples on top: https://www.opentopography.org/

On the other hand, bullet points provide a better overview. My proposal:

What about a landing page which looks like Lars suggested on top, but you can scroll down for more detailed descriptions?

We would use a tiling layout for the bullet points including icons.

See this site as example:  https://breather.com/ Scroll down to "Why businesses choose Breather". 

Or this one: https://www.khanacademy.org/  Scroll down to "Why Khan Academy works"

**Comment by tdbjacobs** [comment]
I'm ok with all of these suggestions. Even if you get rid of the bullet
points, I would tweak the wording as I suggested.

I like the tiling idea.

It might be easiest if you could mock up a couple different options and
then we can evaluate/tweak.

Thanks,

Tevis



Tevis Jacobs
William Kepler Whiteford Faculty Fellow and Associate Professor
Mechanical Engineering and Materials Science
University of Pittsburgh
http://www.engineering.pitt.edu/JacobsLab/
Mail: 636 Benedum Hall, 3700 O'Hara St., Pittsburgh, PA 15261
Office: 538-E Benedum Hall, 412-624-9736
tjacobs@pitt.edu

**Comment by pastewka** [comment]
The current landing page seems fine. We be should not overthink developing it into another direction. I'm closing this issue.
