### ISSUE TITLE
Display list of topographies in a surface

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank#545]
>   * When I click on a Surface, it takes me to the "Topographies" tab
>     (which makes sense), and I see the scrolling gallery (which I like),
>     but I'm actually then not clear on how to view a list of the
>     underlying topographies.
>       o Maybe we should add a "View all topographies from this surface"
>         button.
>       o Or simply a "View all" button that is at the bottom right of the
>         scrolling image gallery. 
> 
> Okay, good idea.
It's not fully clear to me what is supposed to happen when clicking an that button. 

An alternative would be to just have a list below the gallery which is already there from the beginning. Or an extra tab for the list.

**Comment by mcrot** [comment]
Shifting to next major release. More discussion is needed on this one.

**Comment by pastewka** [comment]
The gallery is gone, we now have a list
