### ISSUE TITLE
Save "type of measurement" along with topography

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#546]
> 
>   * Feature request: Consider adding a field like "type of measurement"
>     which contains radio buttons for "Scanning probe microscopy" and
>     "Stylus profilometry" and "Optical profilometry" and "Electron
>     microscopy" and maybe a few others.
>       o I can imagine that it would be useful for a user to filter by
>         type of tool (using protected fields) or analyze all
>         measurements of a certain type.
>       o It would also be useful to be able to color-code plots by
>         instrument type (similar to how we do this in the ACS AMI paper.)
> 
> Yes… We should discuss this. We could of course easily add this field 
> but it may be superseded by something more complete. I was thinking 
> about adding instruments, such that one can define the instrument that 
> was used for a certain measurement. An instrument would then have the 
> property stylus, optical, etc.

I would also like to implement sth more generic like the instruments.

**Comment by pastewka** [comment]
I'm setting this to wontfix for now since #620 is a more practical suggestion.

**Comment by mcrot** [comment]
Since #620 is implemented now and will be released with version 0.15, I'm closing this.
In #620 it's implemented that every measurement saves an instrument type.

**Comment by pastewka** [comment]
Awesome, thank you!


________________________________
Von: Michael Röttger ***@***.***>
Gesendet: Mittwoch, 4. August 2021 17:52
An: ContactEngineering/TopoBank
Cc: Lars Pastewka; Comment
Betreff: Re: [ContactEngineering/TopoBank] Save "type of measurement" along with topography (#546)
