### ISSUE TITLE
Improve tick labels on line plots of topographies

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank#548]
> 
>   * Too many significant digits in the y-axis of the topography plot.
>     (see /Screenshot3.png/).
>       o It should just say "3e-4" instead of "3.000e-4"
> 
> Should be fixed. We should not use the “e” notation on the site, if that 
> is what is currently happening.

So Lars, you prefer "3 x 10**-4" instead, right?

**Comment by mcrot** [comment]
<img width="384" alt="Unbenannt" src="https://user-images.githubusercontent.com/9113541/98536378-033a9680-2288-11eb-85f6-3efe830478e0.png">

**Comment by pastewka** [comment]
Yes exactly. The "e" notation should never be used anywhere in a user-facing interface.

**Comment by pastewka** [comment]
I think this will be fixed with the Bokeh update in #775

**Comment by pastewka** [comment]
Resolved with #1012
