### ISSUE TITLE
Unify JS library loads

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#559]
Currently most of the JS code is loaded from third-party sites like unpkg.com. Maybe problems like #556 are related
to this if someone works behind a firewall. We should unify this. Not sure yet, what is the best approach.

**Comment by mcrot** [comment]
See notes here on CDNs: https://www.smashingmagazine.com/2020/06/django-highlights-wrangling-static-assets-media-files-part-4/

**Comment by pastewka** [comment]
My impression is that the site is delayed by waiting for data from unpkg.com. Couldn't we simply host the JS ourselves? I understand that this is discouraged because it circumvents caching, but...

**Comment by pastewka** [comment]
I think this is a non issue. Loading from unpkg is standard practice and allows the browser to cache things.
