### ISSUE TITLE
Request: Variable column widths

### ISSUE THREAD

**Issue by tdbjacobs** [ContactEngineering/TopoBank#560]
When I look at the table of RMS parameters, it only shows ~10 characters of the topography name. It is sometimes hard to tell topographies apart when their names start out with similar characters. (See screenshots)

Can we implement variable-width columns, where the user can drag the column break outward to see the full name?

<img width="1191" alt="Screen Shot 2020-11-25 at 9 09 04 AM" src="https://user-images.githubusercontent.com/22891610/100240601-bfd75d80-2f00-11eb-923d-98f6953b4b80.png">

**Comment by mcrot** [comment]
Yes, I reduced the topography name to 10 characters to make it fit on the entry page of analyses, where multiple 
analysis functions can be shown. 

Worarounds: If you hover on topography the name, you can see it fully in the tooltip.
If you press "Open", the table is loaded in a new page and you can see the full name.

However, resizing the column width would be nice. I'm going to test this [this library](http://www.bacubacu.com/colresizable/),
maybe it can be easily done with this one.

**Comment by mcrot** [comment]
I've removed the restriction on the first column and added a horizontal scrollbar instead, that was the easiest.
