### ISSUE TITLE
Use of JSONField instead of BinaryField + pickle

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank#573]
Django 3.1 supports a JSONField: https://docs.djangoproject.com/en/3.1/ref/models/fields/#jsonfield

This is probably better suited and more future-proof for
the pickled arguments of analyses.

**Comment by pastewka** [comment]
Related to #426 - we also just upgraded to Django 3.2

**Comment by pastewka** [comment]
Has this been addressed? I thought we now use JSON fields.

**Comment by mcrot** [comment]
No, this is still a BinaryField.

**Comment by pastewka** [comment]
Analyses are no longer stored in database, only parameters are still pickle fields. Should we migrate those?

**Comment by mcrot** [comment]
To a JSON field? Yes. If you write a migration, it would be good to implement a reverse migration, too.
This is easier when we need to switch to another state of a database, one having JSON fields and one the old pickle fields.

**Comment by pastewka** [comment]
There is still a potential problem with numpy arrays that are notoriously difficult to serialize to JSON. Also it is ambiguous if they should become arrays or list when reading. We should simply avoid storing numpy arrays in JSON fields.

This will certainly be better than pickle. Currently, the analysis compare the binary pickle stream to check whether an analysis with the same parameters has run.

**Comment by pastewka** [comment]
Here is an example how to do the migration: https://ijohan.nl/django-south-raw-data-migration/

**Comment by pastewka** [comment]
Closed by #965
