### ISSUE TITLE
Display square root of ACF, not ACF itself

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/TopoBank#578]
We should show the square root of the ACF rather than the ACF since that is directly related to the rms height.

Any opinions @tdbjacobs @AntoineSIMTEK @mcrot ?

**Comment by mcrot** [comment]
Both look very similar, probably because of the log scale. Here some plots for the example data from your paper:

## ACF (unit: µm²)

![example_surface_acf](https://user-images.githubusercontent.com/9113541/111189643-95480800-85b6-11eb-892a-614419f11fc2.png)

## sqrt(ACF) (unit: µm)
![example_surface_sqrt_acf](https://user-images.githubusercontent.com/9113541/111189727-adb82280-85b6-11eb-9802-8ec5af9013f4.png)

So maybe the sqrt only makes sense, if we plot RMS height at the same time as a horizontal line in order to allow a visual comparison?

**Comment by pastewka** [comment]
Yes, they should look identical (except for the scales of the y-axis)!

**Comment by AntoineSIMTEK** [comment]
It makes sense to me that it looks the same on a logscale. 

I still think sqrt(ACF) is better because I can directly read that the RMS is 100nm without having to do a square root in my head.

I am not sure the visual comparison makes sense since the RMS height is exactly the last value.

**Comment by tdbjacobs** [comment]
It might not be obvious to everyone that the last value is the RMS height.
I don't see a problem with somehow identifying it on the plot.

A horizontal line might become too busy if there are many data sets on the
same axes - but maybe marking the final datapoint with a data marker
(circle or asterisk) and then maybe a little explainer that the data marker
indicates the RMS height.

(We might try out a few alternatives and see which, if any, make it clear
and understandable.)

-Tevis




Tevis Jacobs
William Kepler Whiteford Faculty Fellow and Associate Professor
Mechanical Engineering and Materials Science
University of Pittsburgh
http://www.engineering.pitt.edu/JacobsLab/
Mail: 636 Benedum Hall, 3700 O'Hara St., Pittsburgh, PA 15261
Office: 538-E Benedum Hall, 412-624-9736
***@***.***

**Comment by AntoineSIMTEK** [comment]
I was wrong, it is only exactly the RMS - height once the values are uncorrelated

So adding the RMS-height might actually be interesting.

**Comment by pastewka** [comment]
I have to paddle back on this. I think we should leave the ACF as is, but

* Rename the variable bandwidth method to "Scale-dependent Height"
* Display the sqrt of the ACF in that Scale-dependent Height plot
* Also display the height obtained from a filtered PSD

I would do the same for scale-dependent slope and curvature, i.e. show the results of all three methods in that single plot.

This is related to #586.

**Comment by mcrot** [comment]
> I have to paddle back on this. I think we should leave the ACF as is, but
> 
>     * Rename the variable bandwidth method to "Scale-dependent Height"
> 
>     * Display the sqrt of the ACF in that Scale-dependent Height plot
> 
>     * Also display the height obtained from a filtered PSD
> 
Did you implement these changes or is it no longer necessary?

**Comment by pastewka** [comment]
No longer necessary
