### ISSUE TITLE
Download ZIP file should contain normalized NetCDF topography files

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/TopoBank#579]
This is useful to be able to work with the topographies directly in MATLAB etc.

**Comment by mcrot** [comment]
Do you mean the surface container? Currently it contains the original data files.
So the surface container should include one nc file for each topography? 
The topography files should be normalized - how?

**Comment by pastewka** [comment]
Yes, that is what I mean. By "normalization" I mean conversion into a standardized format (i.e. NetCDF). The container should contain an additional .nc file for each original data file.

**Comment by mcrot** [comment]
Just a reminder for me: The meta data file in the surface container has to extended such that two different file formats
can be referenced. Suggestion:
```yaml
    datafile:
      original: example.di
      netcdf: example.nc
```

**Comment by pastewka** [comment]
Can we at this point update the metadata information for this structure? I.e. it would currently only have:
```
datafile:
    original: example.di
```
This way, we wouldn't break things when adding the NetCDF file. See also here: https://github.com/ContactEngineering/SurfaceTopography/pull/79

**Comment by mcrot** [comment]
Yes, good idea!

**Comment by pastewka** [comment]
I suggest that we call the netcdf-entry `squeezed-netcdf` to open the possibility for later adding support for a netcdf representation of the original data, see discussion here https://github.com/ContactEngineering/SurfaceTopography/issues/65

This means `meta.yml` would contain entries:
```yam
datafile:
    original: example.di
    squeezed-netcdf: example-squeezed.nc
    original-netcdf: example-original.nc
```
I will postpone implementation of `original-netcdf` on the `SurfaceTopography` side to the point where that is actually needed.

**Comment by mcrot** [comment]
Okay, `squeezed-netcdf`.
