### ISSUE TITLE
Question: Curvature correction

### ISSUE THREAD

**Issue by tdbjacobs** [ContactEngineering/TopoBank#580]
As of now, we have separate radio choices for "Tilt subtraction" or "Curvature subtraction". But it's not clear to me: does the curvature correction also perform a tilt correction?

In other words, does the curvature correction do ONLY a second-order polynomial (Mx^2+B) or does it do second-order and first-order (Mx^2+Nx+B)?

I assume it does, and if it does, then I would suggest changing the name of that radio button to "Curvature and tilt subtraction".

**Comment by mcrot** [comment]
I think it does both, but I'm not fully sure, because there are even more coefficients (https://github.com/ComputationalMechanics/SurfaceTopography/blob/20a44bdff85b54c7d88f3cf14141902c9851a234/SurfaceTopography/UniformLineScanAndTopography.py#L590). What do you think @AntoineSIMTEK and @pastewka ?

**Comment by pastewka** [comment]
The curvature substraction also corrects for tilt. I am happy to have this renamed.

**Comment by AntoineSIMTEK** [comment]
This is consistent with the docstring:     def __init__(self, topography, detrend_mode='height', info={}):
        """

        Note on periodicity: Detrended Topographies with mode other than
        "center" will have `is_periodic` property set to False.

        Parameters
        ----------
        topography : Topography
            SurfaceTopography to be detrended.
        detrend_mode : str
            'center': center the topography, no trend correction.
            'height': adjust slope such that rms height is minimized.
            'slope': adjust slope such that rms slope is minimized.
            'curvature': adjust slope and curvature such that rms height is
            minimized.
            (Default: 'height')

**Comment by mcrot** [comment]
Ok, thanks, so I will rename it.
