### ISSUE TITLE
opening .xlsx files for ACF,VBM, and PSD

### ISSUE THREAD

**Issue by lthimons** [ContactEngineering/topobank#582]
I have been having issues opening the .xlsx files downloaded from the analysis section. When i try to open any of the excel files in excel I get the following message:

"We found a problem with some content in 'autocorellation_AFM.xlsx'. Do you want us to try to recover as much as we can? If you trust the source of this workbook, click Yes."

Once I click yes, is "repairs" the file and I can use it. I can then enable editing and resave the file myself and the issue disappears. Another issue I have is that the pages in excel either have some of their names cut off (perhaps a character limit issue in excel) or have their names replaced with "Recovered_sheetX" which makes it more difficult to determine which dataset it belongs to. I tried to attach one of the files in question, just in case the issue does not persist when someone else tries to download one of the xlsx files.

I am using the following version of excel:   Version 2101 (Build 13628.20448 Click-to-Run)

[autocorrelation_AFM.xlsx](https://github.com/ComputationalMechanics/TopoBank/files/6043474/autocorrelation_AFM.xlsx)

**Comment by mcrot** [comment]
Thanks, @lthimons for reporting this. This excel version is part of Office 365, correct?
Do you also have an older Excel version and does it have the problems with the same file? 

I'll have to see how to get access to Office 365 in order to test...

**Comment by pastewka** [comment]
Is this still an issue?

**Comment by pastewka** [comment]
Closing this - will reopen when reported again
