### ISSUE TITLE
units in ACF,VBM, and PSD downloads

### ISSUE THREAD

**Issue by lthimons** [ContactEngineering/topobank#583]
In the .txt and .xlsx files downloaded from analysis for ACF, VBM, and PSD, the units are different sometimes. For example, the data from AFM and TEM seem to always be nanometers (either 1/nm or nm or nm^3, for example). But the stylus data is in units of either millimeters or meters, seemingly dependent on the size of the scan. The difference can be seen in the UNCD data if you look at a 1000 um stylus scan vs. a 10,000 um scan, which have units of mm and m respectively. 

This isn't a big issue, but when downloading over 100 topography analyses it made it much more tedious to analyze all of the data together. It either requires the user to write an additional script to determine the units or to go through manually and select which datasets needed their units converted.

Perhaps it would make more sense to simply always report units in meters in the downloaded files?

**Comment by pastewka** [comment]
That is a fair point. My suggestion would be to export both, i.e. have a column that should the current data and another one that should everything in bare SI units (i.e. m^3, etc.).

**Comment by mcrot** [comment]
That sounds reasonable, I will add an additional column as Lars suggests.

**Comment by sannant** [comment]
We discussed this today in the roughness teleconference (@tdbjacobs Tevis, Arushi, Manyu, @sannant Antoine). We prefer to just use one column in SI units. 

This is part of Arushi's efforts to propose a more readable / usable /computer processable excel export .

**Comment by mcrot** [comment]
Okay, if there are no other concerns, I'll implement only one column.
