### ISSUE TITLE
Eliminate term "topobank"

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#588]
Since we want to rename the repo, the term "topobank" should also be removed in the code.
The question is how to name the Django project instead. The term "topobank" is quite short,
"contactengineering" quite long in comparison.

**Comment by pastewka** [comment]
Keep "TopoBank" for the Django-project... I would just rename the repository. We should discuss with @tdbjacobs

**Comment by pastewka** [comment]
I don't think this is worth the effort
