### ISSUE TITLE
Type of Boundary conditions not displayed on Chrme Mac 

### ISSUE THREAD

**Issue by AntoineSIMTEK** [ContactEngineering/TopoBank#594]
<img width="1206" alt="grafik" src="https://user-images.githubusercontent.com/40853209/111323041-d0efda00-8669-11eb-9d6f-5f9318bf678a.png">

Chrome version 89.0.4389.82

**Comment by AntoineSIMTEK** [comment]
But on click the dropdown displays the selected value so it is not dramatic

**Comment by mcrot** [comment]
Thanks. Does this still happen?
If yes, could you please open the web developer console and have a look whether there are any error messages?
Here is a description how to do it on MacOS+Chrome: https://balsamiq.com/support/faqs/browserconsole/#google-chrome

**Comment by AntoineSIMTEK** [comment]
It's ok now.

**Comment by mcrot** [comment]
Ok, thanks, I'm closing this. If it happens again, please reopen.
