### ISSUE TITLE
PSD Fails: Contact Challenge surface.4096x4096.h5

### ISSUE THREAD

**Issue by AntoineSIMTEK** [ContactEngineering/TopoBank#595]
![grafik](https://user-images.githubusercontent.com/40853209/111422495-14405c00-86ef-11eb-95c0-1fab88005761.png)

**Comment by AntoineSIMTEK** [comment]
I changed the surface from non-periodic to periodic recently. When it was all periodic all PSDs calculated successfully.

**Comment by AntoineSIMTEK** [comment]
Interestingly now it worked, but I got a warning on the 8192 surface

**Comment by mcrot** [comment]
Thanks for the email and the issue. I'll ask for increasing the machine's memory as a first measure.

**Comment by pastewka** [comment]
This should be fixed but we need to double check

**Comment by AntoineSIMTEK** [comment]
Excellent works now. 
Note however that the layout is not that nice anymore
<img width="1049" alt="grafik" src="https://user-images.githubusercontent.com/40853209/147566304-72e77b6c-b023-40f2-b1f0-ce9753363e68.png">

**Comment by pastewka** [comment]
The layout will be fixed in PR #775

**Comment by pastewka** [comment]
Thanks for checking
