### ISSUE TITLE
Improve speed when loading landing page for UNCD surface

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#605]
Currently this takes quite long. 
One idea among others is also to cache the go link responses. Of course, the general loading should be optimized first.

**Comment by mcrot** [comment]
Using squeezed NetCDF internally seems to help here. This will be released with version 0.13.0. 
Let's see whether it's fast enough in production and this can be closed.

**Comment by mcrot** [comment]
Probably this could be speeded up more by not loading the topographies at all. They are loaded because of the bandwidth calculation. If this could be done beforehand, loading the page should be much faster, also for 169 measurements.

**Comment by pastewka** [comment]
Fixed by #769 - #775 has additional speed improvements for showing analyses
