### ISSUE TITLE
Add checkbox to select/deselect all topographies

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/TopoBank#623]
This currently requires clicking on > 100 individual topographies for UNCD, see here:

![image](https://user-images.githubusercontent.com/2530391/113185136-5a9ccb80-9256-11eb-96fe-e31eca3a01e9.png)

**Comment by mcrot** [comment]
This question is related: https://stackoverflow.com/questions/39561553/bokeh-widget-callback-to-select-all-checkboxes

I'm trying to add buttons first, because bokeh's checkboxes have only 2 states (no grey), this would be confusing, I think.

**Comment by mcrot** [comment]
The layout of the buttons is a bit difficult, maybe at some point I should try to control bokeh with external JS, e.g. vuejs.
However, now I have this working solution:
![grafik](https://user-images.githubusercontent.com/9113541/118298009-33851b00-b4df-11eb-8a35-cec2630afd67.png)
The (de)selection is now applied to all averages+measurements, which is easier to understand and to layout, I think.

I've changed the color of the toplevel buttons, so the selection buttons look different.

I know the widths of the new buttons is not optimal, unfortunately I didn't manage to have a nicely filling the row working
in all situations (list view, detail view).

What do you think @pastewka?

**Comment by mcrot** [comment]
This is what the page now looks like in total 

## list, all buttons collapsed
![grafik](https://user-images.githubusercontent.com/9113541/118299695-5ca6ab00-b4e1-11eb-86d6-72b1a7312aee.png)

## list, measurements expanded
![grafik](https://user-images.githubusercontent.com/9113541/118300986-d68b6400-b4e2-11eb-8d54-92ef90573fd6.png)
Here some layout problems occur (width does not fit any more), this is already the case in the current version and not related to this issue.


## detail, everything expanded
![grafik](https://user-images.githubusercontent.com/9113541/118299823-895ac280-b4e1-11eb-97a1-c6604f3a3cc5.png)

**Comment by pastewka** [comment]
Looks good! If people complain we can always think of a better solution,but this looks like it does what we want.

**Comment by mcrot** [comment]
Okay, thanks!

**Comment by pastewka** [comment]
I don't like that there is two shades of blue now: The Update button on top left and the buttons below the plots.

**Comment by mcrot** [comment]
Good catch .. this is bokeh's style of "primary", different from bootstrap. But this I can change via CSS, I think.

**Comment by pastewka** [comment]
Sounds good!
