### ISSUE TITLE
Height scale cannot be changed for some text files

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank#637]
After uploading an `.asc` file with a line scan defined simply by two columns (x,y), the height scale could be 
set once (after upload?), but afterwards it cannot be changed any more because it would have been given in the file already:
![grafik](https://user-images.githubusercontent.com/9113541/114895606-ef372a00-9e0f-11eb-90a3-3ac3046d22bc.png)
This seems to be wrong since in the data file there was no height scale defined.

**Comment by mcrot** [comment]
`t.height_scale_editable` is `False`.

**Comment by pastewka** [comment]
This part of the UI has been completely rewritten
