### ISSUE TITLE
Variable Bandwidth

### ISSUE THREAD

**Issue by megannescio** [ContactEngineering/TopoBank#638]
I've been using the Bruker and Keyonce optical profilometers. For both kinds of data files I've uploaded from them, the variable bandwidth has not shown up.  It may be a missing data issue, but they Keyonce machine has really good data retention, so I think it may be a contant.engineering issue.

**Comment by mcrot** [comment]
Thanks for reporting the issue, yes, sounds like a problem with the web app. 
Could you share the data with me ("Michael Röttger") within the web app, so I can have a look?

**Comment by pastewka** [comment]
I think this may be because there are points that are undefined - see #321

**Comment by pastewka** [comment]
Fixed by #768
