### ISSUE TITLE
CSV File and ZAG/ZON Filw From Keyonce

### ISSUE THREAD

**Issue by megannescio** [ContactEngineering/TopoBank#639]
From the keyonce optical profilometer, it can output a CSV file with the raw data of the surface roughness measurements. However, the contact.engineering webapp won't accept the file. I need to first convert it through a matlab code, and then upload the file that the matlab code provides. Additionally, the Keyonce optical profilometer output ZAG and ZON files. The webapp currently does not accept these files but I think it would be beneficial if it did.

**Comment by pastewka** [comment]
Hi @megannescio - we have already implemented a ZON reader that will become available in the next update of the WebApp. For ZAG and CSV, we would need examples. Could you post examples here - ideally examples that we could incorporate into our code for testing purposes (i.e. post some measurement that went wrong).

**Comment by megannescio** [comment]
I can upload all relevant files now, thank you!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
