### ISSUE TITLE
Flipping the Orientation on Bruker Data

### ISSUE THREAD

**Issue by megannescio** [ContactEngineering/TopoBank#640]
When I upload my OPX files from the bruker optical profilometer, it flips the orientation of the data. Attached is a screen grab of the data off of the buker profilometer, and a picture of how that data translates onto the webapp when I upload it. 

![t4_20x](https://user-images.githubusercontent.com/83083564/115905866-ba8d2900-a434-11eb-90f1-524acc7fa44c.PNG)
![bokeh_plot (29)](https://user-images.githubusercontent.com/83083564/115905879-bfea7380-a434-11eb-921e-dec62bbc4c88.png)

**Comment by pastewka** [comment]
Our y-axis is flipped. We could simply flip the y-axis in these plots, but I think what the WebApp does is also how Gwyddion displays it. @megannescio - can you open the file in Gwyddion an post a screenshot here?

**Comment by mcrot** [comment]
@megannescio , thanks for opening this issue. Could you load the file in Gwyddion and post the screenshot. 

I'm not sure whether this is a bug here or this orientation is expected. @pastewka How can we decide, what's correct? Gwyddion could also do it wrong.

**Comment by pastewka** [comment]
There is no issue. This is correct. I am closing this.
