### ISSUE TITLE
RMS height plotted as a curve? 

### ISSUE THREAD

**Issue by tdbjacobs** [ContactEngineering/TopoBank#641]
I'm confused. It appears that, in the Height Distribution analysis, it appears that "RMS height" is being plotted as a Gaussian curve. (screenshots below). I don't understand what that means - the RMS height is just a single number. 

<img width="442" alt="Screen Shot 2021-04-23 at 1 23 25 PM" src="https://user-images.githubusercontent.com/22891610/115907827-633c8800-a437-11eb-9b63-55a0681efd24.png">
<img width="444" alt="Screen Shot 2021-04-23 at 1 24 03 PM" src="https://user-images.githubusercontent.com/22891610/115907829-633c8800-a437-11eb-89c5-1128022b908f.png">

**Comment by pastewka** [comment]
We should simply rename this to "Gaussian fit"

**Comment by mcrot** [comment]
For Slope Distribution and Curvature Distribution we currently have 
"RMS slope" and "RMS curvature". These should then also be named "Gaussian fit", correct?

**Comment by pastewka** [comment]
Yes, rename all of those to "Gaussian fit"

**Comment by mcrot** [comment]
I've renamed the series. In production I'll have to recalculate all height/slope/curvature analyses once the new version is installed.
