### ISSUE TITLE
Upgrade to SurfaceTopography v0.93.0

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#643]
With version v0.93.0, the API of topography has changed. So the analysis functions have to be updated.

**Comment by mcrot** [comment]
Lars:
> Kanonisch erstmal `rms_height` mit `rms_height_from_area` austauschen. Für die "RMS Values" sollten beide berechnet und ausgegeben werden.

**Comment by mcrot** [comment]
@pastewka , @AntoineSIMTEK could you help me on this?

Before v0.93, I had this code in my analysis function for height distribution:
```python
rms_height = topography.rms_height(kind='Sq' if topography.dim == 2 else 'Rq')
```
If I would replace this just by
```python
rms_height = topography.rms_height_from_area()
```
this seems to work also for uniform line scans. But would it also work for non-uniform ones?

It seems that here `rms_height_from_area` is not defined, but `rms_height`?

At the end, do I need this?
```python
if topography.is_uniform:
    rms_height = topography.rms_height_from_area()    # for both dim==1 and dim==2
else:
    rms_height = topography.rms_height()
```

(I've tried to initialize a non-uniform line scan to test, but didn't manage. I'll open another issue on that..)
This is also related to https://github.com/ContactEngineering/SurfaceTopography/issues/86.

**Comment by pastewka** [comment]
In the nonuniform case, there is only a `rms_height_from_profile`. Essentially 'Sq' is `_from_area` and 'Rq' is `_from_profile`. You can do the following:
```
rms_height = topography.rms_height_from_area() if topography.dim == 2 else topography.rms_height_from_profile()
```

**Comment by mcrot** [comment]
Ah, thanks, that was just missing in the documentation.

**Comment by mcrot** [comment]
What I have just seen is that I've forgotten to calculate rms height for area *and* profile for the RMS table. 
That will need some more changes.

**Comment by mcrot** [comment]
I'll do that in an extra issue.

**Comment by pastewka** [comment]
Agreed, this is an extra issue.
