### ISSUE TITLE
Wrong orientation of contact geometry plot

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#649]
I've generated a simple area measurement with a gradient in `y` direction and constant in `x` direction.
See [topo_2D.txt](https://github.com/ContactEngineering/TopoBank/files/6405192/topo_2D.txt).

In the web app it looks like this:

![grafik](https://user-images.githubusercontent.com/9113541/116692725-1b7caa00-a9bd-11eb-9844-765a93745d1f.png)

The contact geometry has this orientation, which is wrong:
![grafik](https://user-images.githubusercontent.com/9113541/116692773-2e8f7a00-a9bd-11eb-8b65-2d707b3141c7.png)

**Comment by mcrot** [comment]
@pastewka , could you import this measurement and have a look at all the other contact plots?
Is the orientation of the other contact plots ok or also wrong?

Probably it is a wrong call of the plot command (`image()`), but I'm not sure yet.

**Comment by pastewka** [comment]
I can fix this together with the other GUI fixes that we talked about today.

**Comment by mcrot** [comment]
Thanks! If any analyses need to be recalculated, let me know, then I have to do it in production after the upgrade.

**Comment by pastewka** [comment]
It's even worse, if width != length I get this.

Topograph view:

![grafik](https://user-images.githubusercontent.com/2530391/116851740-42bcbc80-abf3-11eb-8d84-ba8ac1d70c51.png)

Contact mechanics view:

![grafik](https://user-images.githubusercontent.com/2530391/116851717-33d60a00-abf3-11eb-9645-6f766c7edf1a.png)

`Topography`'s `plot` pipeline function:

![grafik](https://user-images.githubusercontent.com/2530391/116852708-186bfe80-abf5-11eb-802c-fd9e1ee37a5d.png)

So I guess the topograpgy view and `SurfaceTopography` is correct.

**Comment by mcrot** [comment]
Uuups .. let me know if I should have a look.

**Comment by pastewka** [comment]
No worries, I think I know what to do
