### ISSUE TITLE
RMS values: Calculate rms height for both area and profile

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#651]
Currently, for the RMS values analysis, either RMS height for an area or for a profile is calculated and output.
As mentioned in #643 , but values should be output in the RMS table (if possible).

**Comment by pastewka** [comment]
It would be useful to quote the standard nomenclature for these values in the table, i.e. `S_q` and `R_q` etc. Note that not all values that we report may have one of these standardized names.

**Comment by mcrot** [comment]
Ok, now I've implemented this:
![grafik](https://user-images.githubusercontent.com/9113541/117142452-04203100-adb0-11eb-8b22-28547202dbf9.png)

For *Height* and *Curvature* the code just looks whether each method is available:
```
result = [
        {
            'quantity': 'RMS Height',
            'direction': None,
            'area_value': topography.rms_height_from_area()
            if hasattr(topography, 'rms_height_from_area') else None,
            'profile_value': topography.rms_height_from_profile()
            if hasattr(topography, 'rms_height_from_profile') else None,
            'unit': unit,
        },
        {
            'quantity': 'RMS Curvature',
            'direction': None,
            'area_value': topography.rms_curvature_from_area()
            if hasattr(topography, 'rms_curvature_from_area') else None,
            'profile_value': topography.rms_curvature_from_profile()
            if hasattr(topography, 'rms_curvature_from_profile') else None,
            'unit': inverse_unit,
        },
    ]

    if topography.dim == 2:
        dh_dx, dh_dy = topography.derivative(n=1)
        result.extend([
            {
                'quantity': 'RMS Slope',
                'direction': 'x',
                'area_value': None,
                'profile_value': rms_slope_from_der(dh_dx),  # TODO Correct?
                'unit': 1,
            },
            {
                'quantity': 'RMS Slope',
                'direction': 'y',
                'area_value': None,
                'profile_value': rms_slope_from_der(dh_dy),  # TODO Correct?
                'unit': 1,
            }
        ])
    elif topography.dim == 1:
        dh_dx = topography.derivative(n=1)
        result.extend([
            {
                'quantity': 'RMS Slope',
                'direction': 'x',
                'area_value': None,
                'profile_value': rms_slope_from_der(dh_dx),  # TODO Correct?
                'unit': 1,
            }
        ])
    else:
        raise ValueError("This analysis function can only handle 1D or 2D topographies.")
```

For *Slope* I'm not sure. I always used `profile_value` and `area_value` is always `None`. Is this correct?

**Comment by pastewka** [comment]
Okay, the Sq and Rq nomenclature is only used for RMS height. For slope it would be S_\Delta q. Maybe we should have a single column "Values" and then have a coma separated list of values and an optional symbol in parenthesis, e.g. "0.01 (Sq)", "0.02 (Rq)".

**Comment by mcrot** [comment]
I could do this, but then you cannot use the sorting feature any more on the values, e.g. finding the measurement with the highest "Rq". I don't know if someone would need that, what to you think? As alternative, we could also have three columns.

I also have to change it for the downloads - there we should use 3 individual columns I think, because the data may be processed automatically and table cells with multiple values are not practical there. Do you agree?

**Comment by mcrot** [comment]
There is enough space for a third column:
![grafik](https://user-images.githubusercontent.com/9113541/117152913-c4127b80-adba-11eb-9fcd-b1dbe6ecd92c.png)
We may also use decimal powers here instead of the "e" notation.

**Comment by pastewka** [comment]
Don't add a third column. This would mean adding a column for each name that is currently in quantity. I.e curvature would be S_\Delta^2 q, and the line scan one R_\Delta^2 q. We could just have two columns, one saying "Areal value", "Profile value" or similar, but this may also not work for quantities that we may add in the future. Sorting by the value column does not make sense anyway since all values have different units.

**Comment by pastewka** [comment]
(I.e. Sq and Rq are different quantities.) I do like the idea of having quantity specify what it is and then having multiple values that correspond to different ways of computing it, but I agree that this makes things difficult in the download.

**Comment by pastewka** [comment]
(And yes, get rid of the e-notation)

**Comment by mcrot** [comment]
Okay. And what about having a second column next to quantity which shows whether it is "R_q", "S_q", whatever?
For example with name "Symbol"? Then we would have one row for each symbol. This makes it also clear for the download.

**Comment by mcrot** [comment]
I'm trying to implement, what we have discussed. Currently I have some problems with `rms_curvature_from_profile`.
It seems that it is not always implemented in `SurfaceTopography`, not for 2D (wanted to add `x` and `y` direction), 
but also not for 1D uniform line scans. Is this the expected behavior?

**Comment by mcrot** [comment]
PS: I'll rename the analysis function when this here is finished - see issue #653 .

**Comment by mcrot** [comment]
I've made a simple Demo Surface with a 2D topography, a uniform line scan and a nonuniform line scan.
This is what I calculate so far:
![grafik](https://user-images.githubusercontent.com/9113541/117173442-12307a80-adcd-11eb-825b-9ba9dc122ad4.png)

As said before, the 1D curvature is not calculated yet. I'll push my branch and create a PR.
The downloads are not complete yet.
