### ISSUE TITLE
Allow to bypass format detection on upload?

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#658]
Sometimes the format detection fails, just because if precedence, see https://github.com/ContactEngineering/SurfaceTopography/issues/93#.

Idea: The upload form could have an additional dropdown labeled `Format: ` with default `autodetect`.

With that the user could specify a specific format in case the detection fails.

**Comment by pastewka** [comment]
I don't like this suggestion. If the detection fails, we need to fix the detection
