### ISSUE TITLE
Export plot from analysis view as png, svg, pdf

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#66]
Currently there are links in the analysis view for exporting the plots, but they're not functional yet.
We need some export of the results. I haven't found an export functionality in plottablejs, so maybe
other libraries help. Since `plottable`uses `d3` internally, this may be useful:

https://d3export.housegordon.org/

**Comment by mcrot** [comment]
Shifting to 0.19.0 because #775 will probably released there, but I want to do 0.18.0 before.

**Comment by pastewka** [comment]
Sounds good!

**Comment by mcrot** [comment]
After implementing #775, the export of SVG is implemented within the PlotCardView, but not PNG and PDF.
Same for the plot in Contact Mechanics. The maps can be downloaded as PNG.

How to proceed here?

**Comment by mcrot** [comment]
Ok, closing.
