### ISSUE TITLE
Error in excel file while downloading power specttrum data

### ISSUE THREAD

**Issue by ArushiPradhan** [ContactEngineering/TopoBank#669]
![Screenshot 2021-05-25 143902](https://user-images.githubusercontent.com/78487900/119550932-04846a00-bd67-11eb-89a5-8431d54ad5cf.png)
![Screenshot 2021-05-25 143917](https://user-images.githubusercontent.com/78487900/119550946-0817f100-bd67-11eb-8ac0-08b97671875a.png)

**Comment by ArushiPradhan** [comment]
Here is the excel file. As you can see on several sheets it says "recovered"

**Comment by mcrot** [comment]
Hi @ArushiPradhan , unfortunately I didn't get the file.
You could either attach it here on Github to a message or send an e-mail to the given address (not back to GitHub).
It would be also interesting, which Excel version you are using.

**Comment by mcrot** [comment]
Maybe related:
https://stackoverflow.com/questions/61161435/openpyxl-we-found-a-problem-with-some-content
https://foss.heptapod.net/openpyxl/openpyxl/-/issues/1430

Probably this is the reason: Sheet names in Excel files are only allowed to be 31 characters long.
The recovered file has another name for the sheet "Chip4_s1_optical - 1D PSD along y", 33 characters.
Shortened to 31 characters, this is "Chip4_s1_optical - 1D PSD along", the same as for "x" direction.
The sheet name is not unique any more.

So we need a more sophisticated way to shorten sheet names, although this is only a workaround.

**Comment by mcrot** [comment]
It seems to be tricky to get this right. I suggest another approach.
The first sheet could be an "index" sheet with all the other sheets with descriptions and links to each of sheets.

The names of the sheets could then be constructed using a number which simply increments. There could also be a back link
to the index sheet.

Would this be reasonable from a user's perspective?

**Comment by mcrot** [comment]
This will be fixed in the next version 0.15.0 as soon it is online.
There is now an extra sheet "INDEX" which allows to navigate to the individual data sheets.
