### ISSUE TITLE
Incorrect Scaling for OPD Files

### ISSUE THREAD

**Issue by megannescio** [ContactEngineering/TopoBank#674]
The OPD files from the Bruker profilometer give a height scale that is different from what is made from the contact engineering website. 
![1a](https://user-images.githubusercontent.com/83083564/120007880-654eb500-bfa8-11eb-865b-7a6807fc14a6.PNG)

**Comment by pastewka** [comment]
Hi @megannescio - can you share that topography with me? I'll check what's going on.

**Comment by mcrot** [comment]
This is a duplicate of #675, which is fixed. The fix will be available when the next release 0.13.0 is online. Closing.
