### ISSUE TITLE
Add scan_size and pixel size parameters to roughness parameter table

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#677]
This has been described here in another issue: https://github.com/ContactEngineering/SurfaceTopography/issues/92
Use `bandwidth()`: https://github.com/ContactEngineering/SurfaceTopography/issues/92#issuecomment-845222737

**Comment by mcrot** [comment]
@pastewka , @AntoineSIMTEK : 
`HeightContainer.bandwidth()` gives me `upper_bound, lower_bound`.
Is this always identical to `pixel_size, scan_size` or do I have to take anything else into account?

**Comment by mcrot** [comment]
I would add those two values simply as two additional columns in the Roughness Parameter table.

**Comment by AntoineSIMTEK** [comment]
Not as far as I know. Do topographies also return scan_size ?

**Comment by pastewka** [comment]
Uniform:
```python
    lower_bound = np.mean(topography.pixel_size)
    upper_bound = np.mean(topography.physical_sizes)
```

Nonuniform:
```python
    x = self.positions()
    lower_bound = np.mean(np.diff(x))
    upper_bound, = self.physical_sizes
```

I'd be happy to discuss if this is what we actually want, but I think the table should return what `bandwidth()` returns.

**Comment by mcrot** [comment]
Yes, this is what `bandwidth()` returns. I was not sure if this is the data needed by @Rick224339 [here](https://github.com/ContactEngineering/SurfaceTopography/issues/92) .

@AntoineSIMTEK : I think `scan_size` is not always returned.

And if we use `bandwidth()` we should also add it to `test_api.py` in `SurfaceTopography`.

**Comment by mcrot** [comment]
We agreed to just use the result of `bandwidth()`: 
- one additional line with *bandwidth: lower bound*
- one additional line with *bandwidth: upper bound*
