### ISSUE TITLE
Revisiting surface topography visualization

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/TopoBank#679]
I think we should revisit the visualization of the individual topographies completely. In this process, we should also address the related issue #676.

Here are a couple of things I like:
- https://isg.nist.gov/deepzoomweb/view/image/moche
- https://www.zoosphere.net/

They are both based on [OpenSeadragon](https://openseadragon.github.io/examples/in-the-wild/). The repository is [here](https://github.com/openseadragon/openseadragon) and seems to be still maintained. I believe the little scale bar and the overview is done via a [plugin](https://openseadragon.github.io/#plugins). There is a [Django plugin](https://github.com/davidjcox/django-deepzoom) that has not seen updates since 2015. It may not be useful in any case.

OpenSeadragon needs a tiled image format. Several formats are [supported](https://openseadragon.github.io/#examples-and-features). This means what we need is a tool that converts surface topographies to this tiled image format. This functionality could (and probably should) be part of [SurfaceTopography](https://github.com/ContactEngineering/SurfaceTopography). We can then create the tiled image in a celery process, circumventing the memory problem.

**Comment by pastewka** [comment]
After looking into this, I think it should be super simple to implement. I'll write a DZI export filter for `SurfaceTopography` and then we can discuss how to get this into TopoBank

**Comment by mcrot** [comment]
The funny thing is, once we've already had an OpenSeadragon solution in the very beginning of this project (#62) for a short period, now we're coming back. Not sure why, maybe it was easier then. Okay, let's discuss that. With support by the backend it is hopefully easy to implement.

**Comment by pastewka** [comment]
We had discussed this but never implemented it, correct?

**Comment by pastewka** [comment]
See also here: https://github.com/ContactEngineering/SurfaceTopography/pull/104

**Comment by mcrot** [comment]
Yes, it was implemented, but didn't look nice or I had no idea how to have a good color bar for the encoding. Not sure why. We've had it about one week and then I switched to bokeh. Or maybe I thought it was easier overall.

**Comment by pastewka** [comment]
Here is an example to play with:
[openseadragon-test.zip](https://github.com/ContactEngineering/TopoBank/files/6678727/openseadragon-test.zip)

I think it is okay. I don't know how to set the aspect ratio of a pixel which is something we would need. It certainly feels more snappy and responsive than Bokeh. It also solves the problem with having to load the full file. Better would of course to have something like this within Bokeh. (I mean tiled loading of data.)

**Comment by pastewka** [comment]
For implementation we need the following: The tiled image files would be cached (in the S3). We would need a routine that converts the topography to the DZI format. This could well be an analysis function. Django needs to do nothing other than deliver those image files.

**Comment by pastewka** [comment]
Note that we may want to change all map visualization, i.e. also the visualization of contact pressure area etc.

**Comment by pastewka** [comment]
Another thing is that SurfaceTopography should export an image of a scale bar as well. We probably need to stick numbers to it in HTML. See also here https://github.com/ContactEngineering/SurfaceTopography/issues/105

**Comment by mcrot** [comment]
Thanks for the example. The zooming works quite well, at least when all data is locally available.
I expect this would also work with intermediate requests.

You've written that we might exchange all map visualizations. I'm a bit hesitant since we would also
loose then the axes frame, which always show the coordinates of the area you're looking at. Then it would be
more an image than a plot. Also tooltips with specific information at the mouse pointer are not possible any more 
(so far only used for the topography view).

I'm not sure whether the axes or tooltips are relevant from a user perspective or not.
If yes: Maybe we could think of having both visualizations? Or have a detailed look at [DataShader](https://datashader.org/getting_started/Introduction.html)? The latter seems to be made for this use case, although I'm not sure yet how to embed
it into Django.

**Comment by pastewka** [comment]
I agree that we would loose some Bokeh functionality. Let me try to compile a list of pros and cons:

Pros
----
1. Does not load full topography to client
2. Fluent zooming
3. Scale bar
4. Easy to implement

Cons
----
1. Loose single pixel selection
2. Loose x- and y-axis (but have scale bar)
3. Not clear if aspect ratio != 1 is possible
4. Image files contain too much data (it would be better if we had a tiled topography)
5. No scale bar out of the box

The killer argument is really the fact that this seems to be the only way to display large topographies (without us implementing our own JavaScript library).

**Comment by pastewka** [comment]
In terms of cons. It may be possible to implement 1 and 2 as a plugin, and I think 3 should be possible.

**Comment by pastewka** [comment]
That Zoom box is an open plugin, that should be easy to do.

**Comment by mcrot** [comment]
Okay, fine, let's give it a try.

**Comment by pastewka** [comment]
I can try to implement this. One thing to discuss would be whether the generation of the tiled images should be an analysis function.

**Comment by mcrot** [comment]
Maybe we can discuss that on the next meeting. There are different cases:

## The topography image itself
Not sure. From a gut feeling I would say that we use use a Celery task, like I did for generating the thumbnail files, but no analysis. The latter would be more complicated than needed, e.g. you don't want this analysis being chooseable in the UI.

Example thumbnails: Each topography in Topobank has a `renew_thumbnail()` method which can be called within a Celery task: 
https://github.com/ContactEngineering/TopoBank/blob/aed522ff431a4951a98f67e74ed922b921774aa1/topobank/taskapp/tasks.py#L274

Basically you only need to write a Topography method like this:
https://github.com/ContactEngineering/TopoBank/blob/aed522ff431a4951a98f67e74ed922b921774aa1/topobank/manager/models.py#L810

Then call it from a task and start the task with `.delay()` everywhere when needed.
We also have to think about what to do if the files are not ready yet and the user tries to display them etc.

## Maps from analysis results
Here we may just create the tiled images within the analysis, writing the tiles images in the S3 "folder" of the analysis.
And we need to recreate all related analysis in production so everywhere the tiled images are available. Can be done with the management command `trigger_analyses`.

On the other hand it sounds also nice to have everything generated in an analysis. This would need some
reconstruction.

**Comment by mcrot** [comment]
Btw. this could be helpful to implement a "Save image" functionality: https://github.com/KTGLeiden/Openseadragon-screenshot
