### ISSUE TITLE
On maintenance, inform users by showing a special page

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank#688]
Currently, we're shutting down the site completely for updates.
Not sure, how this is done in a better why while being able to update code + database.
This might be an approach: https://github.com/shanx/django-maintenancemode
Another approach is to just let caddy running with a special page when the backend is not reachable.

**Comment by pastewka** [comment]
We now longer shut the site down as the automatic deployment appears to work flawlessly.
