### ISSUE TITLE
Pause and play of measurement topography preview on the surface main page

### ISSUE THREAD

**Issue by RLeute** [ContactEngineering/TopoBank#689]
Dear ContactEngineering developers,

on the "surface main page" (for me i.e. [here](https://contact.engineering/manager/surface/956/)) there is a gallery which shows previews of topographies from the different measurements, it might be good if one could pause the automatic gallery to inspect topographies more in detail and easily compare the different measurements without always switching to the single measurement. Of course it might be good if one could after one pauses the gallery press a play button to start the automatic gallery view again. To make it possible to inspect the whole topography it might be good if the pause-play-button is not in the middle of the picture like in many applications with pause and play.

Thanks for your time,
Richard

**Comment by mcrot** [comment]
Thanks for your suggestion, Richard. Actually play+pause is already possible, just move the mouse on or next to the 
picture until the mouse pointer looks like a hand, without clicking. Move it away to restart the animation.

Does this work for you? Maybe we should add some help text to explain this.

**Comment by RLeute** [comment]
Ah,
perfect that works! a help text or some graphical hint might be useful.

Thanks!

**Comment by mcrot** [comment]
Ok, fine, I will add some help text.
