### ISSUE TITLE
Support for SPM files

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#695]
I've just got a request for supporting SPM files, which seems to be a kind of DI file.

**Comment by mcrot** [comment]
This can now be implemented using https://github.com/ContactEngineering/SurfaceTopography/releases/tag/0.95.0.

@pastewka , in Topobank, there is a list of supported file formats when uploading a file and in the help section.
The DI files are shown like this:
![grafik](https://user-images.githubusercontent.com/9113541/124887315-57dc1000-dfd5-11eb-8fcb-2a4e9805f0b5.png)

Should we list SPM files als separate file format or mention it in the DI section?

**Comment by pastewka** [comment]
Yes maybe we should mention the file extension .spm

**Comment by mcrot** [comment]
This needs to be done in package `SurfaceTopography`, since the file format descriptions are taken from there.
I'll open an issue for that: https://github.com/ContactEngineering/SurfaceTopography/issues/123

So this issue can be closed since the upgrade to SurfaceTopography version 0.95.1 has been implemented.
