### ISSUE TITLE
Deselection takes long in Power Spectrum plot for UNCD

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#696]
The UNCD surface has more than 160 measurements.
When opening the Power Spectrum plot, the deselection and selection of all datasets in the plot
takes much time in the browser. 
Interestingly, another plot like Slope Distribution is quite fast in comparison. The Slope Distribution plot has
2 datasets per topography while the power spectrum plot has 3. Maybe there is some threshold about 350 datasets
after which it becomes slow for some reason?

**Comment by pastewka** [comment]
The main issue we have right now that there is too much data that is transferred to the JS frontend. We need to reduce the amount of data. PR #720 acomplishes this and things should get faster once merged.

However, I understand that @tdbjacobs likes chartjunk PSDs that show every single data point but that is not feasible technically. We could still decide to be able to download the full data set.
