### ISSUE TITLE
Identifying measurements in a surface (maybe an arbitrary index?)

### ISSUE THREAD

**Issue by tdbjacobs** [ContactEngineering/topobank#700]
I had to go through and update a parameter on every measurement for a surface with a very large number of measurements. 

I went to the surface and clicked on the first measurement and updated it, then I clicked on the next arrow ( > ) and updated the second, third, fourth, etc. This worked ok, except I had no idea what my percent completion was. 

Additionally, I got interrupted in the middle and, when I came back and started over, it seemed they were listed in a different order. 

(I may be wrong about the re-ordering, but one way or another, I got myself very lost and had to start over several times to be sure that I updated every single measurement in the surface.)

Is there a way to remedy this? Maybe we could give the measurements an (arbitrary) index, and then display this somewhere on its measurement page: (measurement 72 of 139 for this surface)

I don't want to confuse things further --- maybe there's a better way to handle it. But in any event, I feel it is a common occurrence to need to change a parameter on every measurement in a surface --- so we should make this process a bit easier to do systematically.

**Comment by pastewka** [comment]
This part of the UI has been entirely reworked and it should no longer be an issue.
