### ISSUE TITLE
Maybe use bootstrap icons

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank#702]
Check whether it makes sense to switch the icon set to bootstrap icons: https://icons.getbootstrap.com/

**Comment by pastewka** [comment]
I think it is a good idea anyway to update the design occasional to keep the site feel fresh...

**Comment by pastewka** [comment]
I would prefer to reduce the use of icons in favor of descriptive text. Also, I never understand which fontawesome icons are actually available. If Bootstrap ships with icons, this would also simplify things.

**Comment by pastewka** [comment]
Not sure this is a priority. Fontawesome works fine. Closing it.
