### ISSUE TITLE
Permissions of published surface not set correctly when run outside of docker

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank#704]
This doesn't seem to be relevant for production, but is annoying in development just running locally with runserver:
When publishing, the permissions of the creator are not revoked from the creator, e.g. `change_surface`.
The data can still be changed.

I've done quite some investigation on this but haven't found a solution yet. It seems that
`remove_perm` of `django-guardian` does not work here for some reason. Maybe this is related to delayed commits or similar,
I don't know yet. Maybe this is related to the changes for release 0.15, especially for instrument data?!

**Comment by mcrot** [comment]
This is still open and throws an exception:
![grafik](https://user-images.githubusercontent.com/9113541/135852274-ba609d4f-648e-4662-b1f8-1faf3282289d.png)
Under docker, the permissions are correctly revoked. Shifting this to the next release.

**Comment by pastewka** [comment]
I've just now encountered this in the testing instance

**Comment by pastewka** [comment]
I think what is happening is that superusers are not able to publish:

This line

https://github.com/ContactEngineering/topobank/blob/d20201329e52ddc81e115d30da35b13354650095/topobank/manager/models.py#L365

excludes superusers. It seems that even if you are a superuser, you cannot remove any permissions. My suggestions is to simply not allow publication from staff or superusers.

**Comment by pastewka** [comment]
This only affects superusers, not staff users
