### ISSUE TITLE
Tip radius/resolution should not be a mandatory field

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/TopoBank#705]
Currently, you have to enter the tip radius, but there are situation where an AFM etc. measurement was taken but the tip radius is unknown. There should be a possibility to leave that information unspecified.

**Comment by mcrot** [comment]
Do we need to fix this today?
Does this also apply for "microscope-based" and the resolution?

**Comment by pastewka** [comment]
No we don't need to fix this today and yes this also applies to the "microscope-based" resolution.

**Comment by tdbjacobs** [comment]
Perhaps we can have a small explainer below it that says “if a tip radius is entered, the data will be analyzed to remove tip-radius artifacts”

(Same for resolution, but only after some implementation of that artifact-detection)

**Comment by mcrot** [comment]
Okay, I'll add such an explainer. The artifact detection should will be available with the next release of the web app.

**Comment by mcrot** [comment]
@pastewka , I'm just having a look at the current master of SurfaceTopography.
If a resolution is given for an instrument, is it really used?
So is the artifact detection also implemented for microscope-based measurements?

In `SurfaceTopography/Generic/ReliabilityCutoff.py` I've only found the usage of `info['instrument']['tip_radius']`, but  
`info['instrument']['resolution']` seems to be not used. The latter is set if `resolution` is set.

**Comment by pastewka** [comment]
You are right, manual resolution is not used. I'll implement that! Thanks for noticing.

**Comment by pastewka** [comment]
Hi @mcrot - can you check whether this fixes it: https://github.com/ContactEngineering/SurfaceTopography/pull/146

**Comment by mcrot** [comment]
Looks good!

**Comment by pastewka** [comment]
The fix has just been released in 0.97.4 https://github.com/ContactEngineering/SurfaceTopography/releases/tag/0.97.4

**Comment by mcrot** [comment]
Thank you!
