### ISSUE TITLE
Surface analysis taking too long

### ISSUE THREAD

**Issue by ArushiPradhan** [ContactEngineering/TopoBank#707]
Hi,
I am having difficulty loading analysis of my surfaces. There are a total of 86 measurements which is probably why it is taking such a long time but I have had no success and I have been running it for hours. It shows 0% loading.
![image](https://user-images.githubusercontent.com/78487900/131518030-92802dcf-540a-4e8c-be16-555353dd0c51.png)

Thank you,
Arushi

**Comment by mcrot** [comment]
This seems to be related to #708. I confirm that analyses are currently not working, it seems like a process has been killed because memory was exhausted. I've restarted the worker processes and recalculate the missing analyses and let you know.

**Comment by mcrot** [comment]
Please have a look if your analyses have been completed.

**Comment by ArushiPradhan** [comment]
It is working now, thank you!

**Comment by mcrot** [comment]
Thanks! I'm closing this here, but I've opened another issue for technical root analysis: #709 
Let me know if this happens again.
