### ISSUE TITLE
Surface Analysis not completing

### ISSUE THREAD

**Issue by ncmiller15** [ContactEngineering/TopoBank#708]
![Contact Enginering Screenshot 2021-08-31 104205](https://user-images.githubusercontent.com/79552180/131523506-c5b6601a-730e-405a-8b8d-48f9a1513ba1.png)

When I click analyze surface the website moves to the results screen, but the analysis stays on pending indefinitely.  I have attached a screengrab of the issue.

**Comment by mcrot** [comment]
Thanks for opening the issue. Could you share the surface with me ("Michael Röttger"), or send a link if already shared, so that I can see which surface is affected here?

**Comment by mcrot** [comment]
Well now I see, that analyses were affected in general because some process was killed, probably because of memory exhaustion.
Issue #708 is a duplicate.

**Comment by mcrot** [comment]
I've restarted the worker instances. Please have a look if your analyses have been completed.

**Comment by ncmiller15** [comment]
Michael, I just checked and the analysis is running to competition. Thank you for finding a fix! Thanks,Nate Sent from Mail for Windows From: Michael RöttgerSent: Wednesday, September 1, 2021 8:26 AMTo: ContactEngineering/TopoBankCc: ncmiller15; AuthorSubject: Re: [ContactEngineering/TopoBank] Surface Analysis not completing (#708) I've restarted the worker instances. Please have a look if your analyses have been completed.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mcrot** [comment]
Thanks, Nate! I'm closing this here, but I've opened another issue for technical root analysis: #709
Let me know if this happens again.
