### ISSUE TITLE
Check setting when switching to Celery version 6.0

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank#710]
With Celery 6.0 the behavior of handling incomplete jobs changes on connection loss:

https://docs.celeryproject.org/en/stable/userguide/configuration.html#worker-cancel-long-running-tasks-on-connection-loss

Check if `True` is a an appropriate setting.

**Comment by pastewka** [comment]
I don't think this is an issue. Celery will report those tasks as failed, and if that is the case this will superseded the self-reported task (which would be running).
