### ISSUE TITLE
Passing unit to `detrend`

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/TopoBank#715]
Why does the unit need to passed here @mcrot ? This will no longer work with the newer interface.

https://github.com/ContactEngineering/TopoBank/blob/8f530b475e4932b3a999a7bed66e57affb064cfb/topobank/manager/models.py#L630

**Comment by mcrot** [comment]
Not sure, maybe this was a workaround. I will remove it when resolving #698 for version 0.16.

**Comment by pastewka** [comment]
Sounds good. I'm not even this works, I think unit will be overriden with whatever has been passed to the constructor.

**Comment by mcrot** [comment]
Do channels also have a `unit` property now or is this still exposed through the `info` dict?

**Comment by pastewka** [comment]
They do have a `unit` property now.
