### ISSUE TITLE
Height scale applied twice on import

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/TopoBank#718]
We currently have two modes of providing `height_scale`:
* From the data file, if the height scale is clear
* By the user, if the height scale is unclear, e.g. for text files that may be provided in any arbitrary scale and do not have metadata

Currently, `meta.yml` contains the height scale independent of source. This leads to the height scale being applied twice for cases where it comes from the data files, both in the import command of `TopoBank` and in the container read of `SurfaceTopography`.

My suggestion is to export this information to `meta.yml` only if it is not provided by the data file, i.e. if `height_scale_editable` is true.

**Comment by mcrot** [comment]
Oh, good catch! Your suggestion sounds reasonable, I'm going to implement it so.
