### ISSUE TITLE
Provide link to github discussions

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/TopoBank#722]
GitHub has a new feature called discussions that is ideal for user feedback (I think). I just enabled it. We should add a link call "Feedback" to the toplevel menu here linking there:

![grafik](https://user-images.githubusercontent.com/2530391/134057016-c80778ac-a496-481f-b352-b6499615f479.png)

**Comment by mcrot** [comment]
Great idea, that seems to be more low-threshold than opening an issue.
