### ISSUE TITLE
Continuing Average of 1D PSD Along X after data is completed

### ISSUE THREAD

**Issue by megannescio** [ContactEngineering/TopoBank#724]
When the average of 1D PSD along X is computed along the X -axis, I've noticed that the line continues past the end of the data. i suspect this  is a bug, but I am not sure. A screenshot has been included. 
![average picture](https://user-images.githubusercontent.com/83083564/134232443-e07286bd-5bd5-49fc-87b0-beec1fd212e5.PNG)

**Comment by mcrot** [comment]
@megannescio , I would like to look at the exact same data, but I don't know which surface this is.
There are many with a name which start with "BJP Inconel 625.."

Could you share the surface with me in TopoBank by clicking "Share"? Or post the URL of the surface, so I know its ID?

**Comment by megannescio** [comment]
Yes, my apologies! The surface is BJP Inconel 625, 0hrs sintered.  I have also shared it with you.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by mcrot** [comment]
Thanks! Unfortunately I cannot see it among the shared surfaces. Maybe there is bug with sharing?!
This is my profile:
![grafik](https://user-images.githubusercontent.com/9113541/134373796-02356d92-4fe9-4808-9a98-ca84e99fbe13.png)

Did you share it with me? If you press "Permissions", you can click on the names and see the profile, i.e. also the ORCID ID.

**Comment by megannescio** [comment]
Whoops, I accidentally shared it to the wrong person. Again, my mistake. I think you can see it now!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by mcrot** [comment]
Thanks! Now I can see it, I'll have a look. You can delete the wrong share in the Sharing overview:
![grafik](https://user-images.githubusercontent.com/9113541/134375729-93f629b8-31f6-4110-89ab-c6992a708c21.png)

**Comment by mcrot** [comment]
Hi @megannescio , this is a bug. Thank you for reporting.
We've just done a lot of refactoring and with the new version, and the filtering of unreliable data, the plots looks like this:
![grafik](https://user-images.githubusercontent.com/9113541/134483274-e4d74948-1464-4c96-9873-31dc78e2c3e6.png)
So this issue seems to be fixed. This fix will be available with the next version 0.16.
