### ISSUE TITLE
Show reliability cutoff in "Data integrity" tab and roughness parameter table

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/topobank#727]
It would be useful to know the reliability cutoff. My proposal is to:
* Show the value in the instrument tab
* Indicate it in the bandwidth plot by showing the unreliable portion of the bandwidth in a different color

**Comment by pastewka** [comment]
As an ammendment: I think we should not use the instrument tab for this, but at an additional tab "Data integrity" that could show this for the measurements. For a surface, data integrity should list the measurements without any reliable data and maybe in a separate section those with less than a decade of reliable data.

**Comment by mcrot** [comment]
This is simply `topography.short_reliability_cutoff()`, correct? 
From that code I assume that the unit of the cutoff is the unit of the topography.

**Comment by pastewka** [comment]
Yes. That function can return None if it does not know how to compute the cutoff or if the whole measurement is reliable.

**Comment by mcrot** [comment]
Okay, thanks. So I'll interpret `None` as "cannot compute reliability cutoff, so all data is assumed to be reliable".

**Comment by mcrot** [comment]
This value could also be added to the roughness parameter table.

This issue is directly related to #825 .

**Comment by mcrot** [comment]
Renamed this issues since the coloring in bandwidth plot has already been implemented (#825).

**Comment by pastewka** [comment]
This is now shown as a badge on the topography card
