### ISSUE TITLE
Recalculate surface analyses on topography deletion

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank#729]
This is missing so far.

**Comment by mcrot** [comment]
No, it is implemented. All surfaces analyses are deleted after topography deletion. So they are recomputed id requested again.
However, they could also be triggered automatically.

**Comment by pastewka** [comment]
I've disabled automatic triggering of analysis throughout. Since we now have batch upload, if a user uploads 100 data files this would trigger 2000 Celery tasks, essentially blocking the worker machine for a long time. Running calculations on demand seems to be the simplest load-balancing strategy.
