### ISSUE TITLE
Labeling graphs for analysis of multiple surfaces

### ISSUE THREAD

**Issue by ArushiPradhan** [ContactEngineering/TopoBank#742]
Hi,
While analyzing multiple surfaces at the same time it would be really helpful if the graphs are labeled at least for the average PSDs. For example:
![image](https://user-images.githubusercontent.com/78487900/138108724-bc8c59b3-b94f-4be6-90f0-56c8991d4483.png)
here I am analyzing 3 different surfaces and the average PSDs show up as different colors but they are not indexed.

Thank you,
Arushi

**Comment by mcrot** [comment]
You mean labelled in a legend?

As a workaround, you could press on "Average / Measurements", then "Deselect all", and then switch on and off 
the averages in order to see which one is which color.

**Comment by pastewka** [comment]
I think this makes sense. We didn't want legends because there may be lots of lines in a plot, but there will always be only a few averages. This will also help spotting what the average is.

As an additional suggestion, we could decide to plot averages always in black (and use dash to distinguish between different digital twins).

**Comment by mcrot** [comment]
Hm - it's more complicated than I though initially. 

For some analysis functions there are multiple lines per surface.
For example, for PSD, you have 6 lines per surface:
![grafik](https://user-images.githubusercontent.com/9113541/144416363-efcfe2af-db79-43d0-a59a-94e380c0f447.png)

So if you have 3 surfaces, the legend will be too long with 18 entries.

And if we have only black, then the line styles need to distinguish between surface *and* data series,
so we would need 18 different line styles.

**Comment by pastewka** [comment]
Okay, let's stash this for the release you are currently preparing and push it into 1.0.0.

**Comment by pastewka** [comment]
We should more generally rethink how to visualize a large amount of data. There is also an old connected issue https://github.com/ContactEngineering/TopoBank/issues/79
