### ISSUE TITLE
Avoid scientific notation on linear axis

### ISSUE THREAD

**Issue by AntoineSIMTEK** [ContactEngineering/TopoBank#743]
<img width="224" alt="grafik" src="https://user-images.githubusercontent.com/40853209/138099774-9128ded0-8926-43f9-bd33-1aeb9c3f2ff1.png">

Here the x and y axis use $2x10^2, 3x10^2$ ,  but it would better to use simply 200, 300 for readability.

This comment only applies to linearly scaled axis !

**Comment by mcrot** [comment]
Good point. Would do you think @pastewka?
We could also discuss that in the next meeting.
