### ISSUE TITLE
Author affiliation for published datasets

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/TopoBank#762]
We currently do not collect affiliations of authors but we absolutely should. I suggest a free test field such as the authors themselves.

**Comment by mcrot** [comment]
We would need one affiliation per author correct? 
So eventually we need individual author fields. This is related to #732. 

Or would it be sufficient to let the user enter a line like "University of Pittsburgh, University of Freiburg, ..." where each entry should match an entry in the authors line .. but this would be error-prone.

Another idea is that each user can create and edit personal "Author" datasets, optional with ORCID and affiliation, regardless whether these people use the web app or not. So these authors are independent from the users, but may be linked to users.
So one would add all potential authors in a personal list and use them. 

If we had working groups, we could also share those "Author" datasets in a group. Or alternatively, just share the Authors list with individual people, like a surface.

**Comment by mcrot** [comment]
This has already been implemented and is online, correct?

**Comment by pastewka** [comment]
Yes it is online 
________________________________
Von: Michael Röttger ***@***.***>
Gesendet: Donnerstag, 27. Oktober 2022 18:05
An: ContactEngineering/TopoBank
Cc: Lars Pastewka; Author
Betreff: Re: [ContactEngineering/TopoBank] Author affiliation for published datasets (Issue #762)

**Comment by mcrot** [comment]
Closing.
