### ISSUE TITLE
Bug in management command `fix_height_scale`

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#763]
In `topobank/manager/management/commands/fix_height_scale.py`
there are the lines (from line 86 on) 

```python3
            if (not height_scale_editable) and math.isclose(channel.height_scale_factor, topo.height_scale):
                num_different_factor += 1
                if not options['dry_run']:
                    topo.height_scale = channel.height_scale_factor
                    do_save = True
```
Here the measurements height scale is overridden with the channels `height_scale` if they are already equal.
This is wrong. It should be overridden, if they are not equal:
```python3
            if not (height_scale_editable or math.isclose(channel.height_scale_factor, topo.height_scale)):
                num_different_factor += 1
                if not options['dry_run']:
                    topo.height_scale = channel.height_scale_factor
                    do_save = True
```

**Comment by mcrot** [comment]
Here a test is missing in `topobank/manager/tests/test_commands.py`. There is one for fixing the
sizes, but not for fixing the height scale factors.

We probably need to run this again on the production database.

**Comment by pastewka** [comment]
Fixed in https://github.com/ContactEngineering/TopoBank/pull/758

**Comment by pastewka** [comment]
(No test yet, will add one.)

**Comment by mcrot** [comment]
I've cherry-picked 23f8e43a7e80622b8a6055f7d491ef2adcae04b4 from PR #758 here.
