### ISSUE TITLE
Avoid loading full topography in Django server

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/TopoBank#769]
The Django server should never need to load the full topography. This should only happen in Celery tasks. This is because the memory fo the Django server is limited but Celery tasks will run on big-memory big-CPU machines.

I do think the server currently loads the full topography at the following occasions:

1) Computing the bandwidth
2) Rendering plots

My suggestion it do 1) when computing the squeezed datafile (see PR #768 for how this is handled for determining whether the topography has undefined data points, which also required actually reading the data). Point 2) will be fixed with PR #758.

PR #768 currently has a specific database field for `has_undefined_data` attribute. If we now add the bandwidth, it may make more sense to just store a JSON with metadata on the topography.

**Comment by pastewka** [comment]
Also `TopographyUpdateView.form_valid` runs `renew_squeezed_datafile` directly in Django. Can't we use Celery to do this? I understand that `renew_topography_thumbnail` and `renew_analyses_related_to_topography` depend on `renew_squeezed_datafile` to have completed, but I think this can be solved using Celery's `chain` (see https://docs.celeryproject.org/en/master/userguide/canvas.html).

**Comment by mcrot** [comment]
Yes, I agree that Celery's chains are the way to go here.

**Comment by pastewka** [comment]
Another comment: @mcrot was unhappy that there may be some computation (currently determining of undefined data points) when constructing the squeezed datafile. I didn't want to open it a second time to look at it, but we can actually determine whether a topography has undefined data from the squeezed datafile without reading it completely. (Just check for the existence of a `mask` variable, the NC reader does that automatically.) So we may move this out of the construction of the squeezed file.
