### ISSUE TITLE
`TopographyForm` and `TopographyWizardUnitsForm` has lots of redundant code

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/TopoBank#770]
It seems like most of the code of `TopographyForm` and `TopographyWizardUnitsForm` is identical. Can this be merged to avoid code duplication?

**Comment by mcrot** [comment]
Most of the code of both classes is already shared through their common base class `TopographyUnitsForm`.
Maybe some more can be shared which is in `__init__` or `Meta.fields`. Do you mean that code?

**Comment by pastewka** [comment]
Yes exactly, that is the code that I am talking about. Essentially the construction of the form, i.e. which fields to show, is identical and duplicate.
