### ISSUE TITLE
Logscale labels have different font sizes in exponents

### ISSUE THREAD

**Issue by sannant** [ContactEngineering/TopoBank#771]
<img width="117" alt="grafik" src="https://user-images.githubusercontent.com/40853209/143850811-698429b2-23ed-44a7-ba48-80d7db0654d4.png">

(Powerspectrum view of the published NCD)

**Comment by mcrot** [comment]
Ups, it seems like some brackets are missing in JS code. Thanks.

**Comment by mcrot** [comment]
@mcrot Could you send a link here? I cannot see this. The y axis of the published NCD
hasn't got high tick values so high in my view here.
