### ISSUE TITLE
Unexpected keyword in autocorrelation_for_surface

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#772]
```python3
Traceback (most recent call last):
  File "/app/topobank/taskapp/tasks.py", line 131, in perform_analysis
    result = analysis.function.eval(subject, **kwargs)
  File "/app/topobank/analysis/models.py", line 288, in eval
    return self.get_implementation(subject_type).eval(subject, **kwargs)
  File "/app/topobank/analysis/models.py", line 340, in eval
    return pyfunc(subject, **kwargs)
TypeError: autocorrelation_for_surface() got an unexpected keyword argument 'num_points'
```

**Comment by pastewka** [comment]
`num_points` is not supported. It is now called `nb_points_per_decade` I think.

**Comment by pastewka** [comment]
(Not sure where the `num_points` comes from.)

**Comment by pastewka** [comment]
Duplicate of #765

**Comment by mcrot** [comment]
Probably `num_points` come from old analysis entries in the database. Once we decided
to save all arguments in the database, also the default ones in order to be able to reproduce the analyses.
There is
```
docker-compose -f production.yml run --rm django python manage.py save_default_function_kwargs --dry-run
```
but it only adds new arguments which have not existed before. 
It is similar to migrations in Django . This is probably fixed by rerunning all autocorrelations for surfaces.

I'll shift this to the next version in order to see whether this is true.

**Comment by pastewka** [comment]
Sounds good

**Comment by mcrot** [comment]
Rerunning fixed it.
