### ISSUE TITLE
Choose unit for analyses automatically

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank#78]
Currently the unit of the first analysis is used. Find optimal unit for multiple analyses.

**Comment by pastewka** [comment]
The average now chooses an optional unit through the `suggest_length_unit` function of `SurfaceTopography`'s container. I guess this issue generally applied to what the user sees which may actually be arbitrary combinations of topographies and surfaces.

**Comment by pastewka** [comment]
I am closing this since it is partially implememted.
