### ISSUE TITLE
Name for Contact Mechanics tab "Actions"

### ISSUE THREAD

**Issue by sannant** [ContactEngineering/TopoBank#792]
A user was looking for 

- Where to configure simulations parameters 
- Where to download the results

and couldn't find where.

My suggestion for more intuitive user interface: 

Rename "Actions" to "Simulaton parameters"

and put it on top in the tab list (since it is what you need to do before looking at the results)

Bring the download button to top level , e.g. as a tab.

**Comment by mcrot** [comment]
Maybe we could rename "Actions" to "Parameters / Download"?

I'm a bit hesitant to put it on top, because it's no longer immediately clear that you can select individual points in order to get more information on them. But maybe that's okay, because you see a hint if you select another tab.
What do you think @pastewka ?

**Comment by pastewka** [comment]
Sounds good. I am working on this anyway - let me take care of it. I am actually thinking about redesigning the whole page - am not happy with it. Any suggestions are welcome... (also to make clearer that the points can be clicked, etc.)

**Comment by mcrot** [comment]
One option would be to open a modal window when clicking on a point and showing all details in this modal window. This would use less space on the page, but I'm not sure, if this would affect the usability. I imagine that users want to visually compare e.g. the contact geometry for different loads by clicking first one point, then the other?!

**Comment by mcrot** [comment]
So far, this will be solved in PR #775 by using "Parameters" instead of "Actions".

**Comment by mcrot** [comment]
Fixed by PR #775, used "Parameters" now. Is this ok, @sannant or should it be "Parameters/Download"?

**Comment by mcrot** [comment]
Ok, closing. Please reopen, if "Parameters" is not sufficient.
