### ISSUE TITLE
Store raw data under a unique prefix

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/TopoBank#801]
Raw files are currently uploaded to the same prefix. This means Django attaches suffixes to avoid file name collisions. We should just store the raw file under the prefix that we currently use for derived data and use the original file name.

This leads to problems when downloading containers, as all files are in the toplevel ZIP folder and this could lead to name collisions. We should probably also introduce a (consecutively numbered) subdirectory for each measurement in the container.

Any thoughts on this @mcrot ?

**Comment by mcrot** [comment]
Currently there is already some code which prevents name collisions for measurements in the ZIP container. 
If  a filename is already used in the ZIP, a counter is added to the file name.

Probably this could be solved in a better way. We could use subdirectories which name is a number. A natural choice would be just the measurement id in production as this is already used in the URL. If we don't want to
further expose these numbers, we could also use a consective number, e.g. over all measurements for a surface or over all measurements in the ZIP.

I'm not sure what you are meaning here with derived data - the analyses?

>  We should just store the raw file under the prefix that we currently use for derived data and use the original file name.

The prefix or subdirectory we use for measurement files are currently named with the user id.

**Comment by pastewka** [comment]
We don't need the user prefix, in particular since we want to implement transfer of ownership at some point. See #706

**Comment by pastewka** [comment]
Files in the ZIP container should be prefixed by a unique consecutive topography id, e.g. `001_random.txt`, to avoid name collisions. If there is more than one digital surface twin in the container, then add an additional twin index, e.g. `01_001_random.txt`.
