### ISSUE TITLE
Increase increment in changing the number of iterations in contact mechanics

### ISSUE THREAD

**Issue by sannant** [ContactEngineering/TopoBank#809]
currently the max. number of iterations increasers in increments of 1 when pressing the arrow. 

100 or 1000 would be more useful.

**Comment by mcrot** [comment]
Okay. Would 100 be better than 1000? 
What would be reasonable for the allowed maximum for the maximum number? 
We should not allow practically infinite iterations.
At the moment, the maximum value you can enter is 1000. Given that an increment of 1000 is not that useful either ;-)

**Comment by AntoineSIMTEK** [comment]
Ah sorry then 100 of course

**Comment by pastewka** [comment]
I think 100 is reasonable.

**Comment by mcrot** [comment]
The easiest would be to use then `step` argument of the HTML `input` element.
Then the values would also be fixed at 100, 200, 300, .., 1000.
I assume this is okay for you, isn't it?
