### ISSUE TITLE
Selection of surfaces and topographies without extra button press

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#81]
Currently an extra button press is needed in *Analyses* view and *Surfaces* view in order
to select topographies and functions for this session. They should be selected
immediately after selected in the select boxes.
Then also the number of buttons in the *Surfaces* view can be reduced and labelled better.

**Comment by pastewka** [comment]
This is no longer the case in the current version, correct @mcrot

**Comment by mcrot** [comment]
Yes, I'm closing this.
