### ISSUE TITLE
Show author affiliations

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/TopoBank#811]
We now collect author affiliations but do not show them anywhere (and just pass them on to DataCite). I propose to add a tab "Authors" on this page that shows this information for published datasets:

![image](https://user-images.githubusercontent.com/2530391/160124311-d136b6a3-542b-4975-b4c2-a776c9ff9dd4.png)

**Comment by mcrot** [comment]
Good Idea, should be easy to to. As table or a formatted list?

**Comment by pastewka** [comment]
Sounds good

**Comment by pastewka** [comment]
Am Montag, dem 28.03.2022 um 00:58 -0700 schrieb Michael Röttger:

Sounds good.

**Comment by mcrot** [comment]
Hi @pastewka , this functionality has already been implemented and is online.

**Comment by pastewka** [comment]
Fantastic!
