### ISSUE TITLE
Rename container ZIPs

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#815]
For new containers, use
- "ce-"+shorturl+".zip" for published surfaces
- "digital_surface_twin.zip" for unpublished surfaces

**Comment by mcrot** [comment]
There is also the case of multiple digital surface twins in one container, e.g. when downloading a selection.
Maybe in this case we should think of a different name like "digital-surface-twin-selection.zip".

**Comment by pastewka** [comment]
Or just 'selection.zip', because this is then not really a DST.

**Comment by mcrot** [comment]
Actually it is a list of complete digital surface twins. Even if you select only two measurements from different surfaces,
both surfaces will be included in the selection.
