### ISSUE TITLE
Download as png doesn't work

### ISSUE THREAD

**Issue by tdbjacobs** [ContactEngineering/TopoBank#817]
I'm using Chrome (Version 99.0.4844.84 (Official Build) (x86_64)) on a mac. And when I go to Contact Pressure and click on "Download as PNG", it appears that nothing happens.
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/22891610/161883333-8c9ae854-ff3c-44dc-8554-f8d5667a67b6.png">

**Comment by mcrot** [comment]
Hi @tdbjacobs , for me it works in Chrome. Is this still an issue for you?

**Comment by tdbjacobs** [comment]
I just tried it. It works for me now.
Best,
Tevis

**Comment by pastewka** [comment]
Okay, thanks. Closing this.
