### ISSUE TITLE
Consider restructuring the "Analysis" toolset

### ISSUE THREAD

**Issue by tdbjacobs** [ContactEngineering/topobank#818]
Personally, I think it is currently hard to find the surface-performance analysis tools, such as Contact Pressure and Contact Distribution. 

The problem is that, when you click Analyze, all of the surface-analysis metrics are each a different standalone tool (PSD, ACF, VBM, etc.); however, all of the performance metrics are hidden under one tool called "Contact Mechanics". (screenshot below). 

I think we might want to restructure the "Analysis" toolset to make everything easier to find. Maybe we can follow the logic implied by Figure 1 of the web-app paper, where there is a hierarchy: first the user selects "Analyze"; then the user chooses from two options: "Statistics" or "Contact". If they choose "Statistics", then it brings up all those options (parameters, PSD, ACF, etc.). If they choose "Contact", then it brings up all those options (pressure distribution, contact area, etc.)

Although I would suggest renaming the various top stages of hierarchy:
Instead of "Analyze", we can call this "Analytics"
Instead of "Statistics", we can call this "Surface statistics"
Instead of "Contact", we can call this "Surface performance"

These are just suggestions ---- happy to discuss further. 

![image](https://user-images.githubusercontent.com/22891610/161883564-493d345e-d0bd-46bf-8253-6d519001b3a8.png)

**Comment by pastewka** [comment]
Splitting the contact analysis into multiple ones that are accessible from the landing page will be a major reorganization of the code. We need to discuss how to actually design the user interface, and when and if to implement this.

**Comment by tdbjacobs** [comment]
OK. Didn't realize that.

Perhaps we can roll this into a larger discussion about how to implement
"plug-ins"

-Tevis



Tevis Jacobs
William Kepler Whiteford Faculty Fellow and Associate Professor
Mechanical Engineering and Materials Science
University of Pittsburgh
http://www.engineering.pitt.edu/JacobsLab/
Mail: 636 Benedum Hall, 3700 O'Hara St., Pittsburgh, PA 15261
Office: 538-E Benedum Hall, 412-624-9736
***@***.***
