### ISSUE TITLE
Show unreliable bandwidth in different color in bandwidth plot

### ISSUE THREAD

**Issue by sannant** [ContactEngineering/TopoBank#825]

**Comment by mcrot** [comment]
This would be a small line in each topography bar and can be different for each measurement, correct?

**Comment by sannant** [comment]
yes. or like half of the bar in red

**Comment by mcrot** [comment]
@yaelgail , after finishing this issue here, you could continue with #727, which is directly related.
You can talk with @pastewka about how it should look like.
