### ISSUE TITLE
Stylus Data is not being cut off at the cutoff point

### ISSUE THREAD

**Issue by Vchadha2** [ContactEngineering/topobank#826]
My stylus data is not being cut off at the cut-off point and is being included in the PSD as a whole. My file type is OPDx

**Comment by pastewka** [comment]
Can you share the DST with me on contact.engineering?

**Comment by Vchadha2** [comment]
https://contact.engineering/manager/surface/1242/
<https://contact.engineering/manager/surface/1242/>
There are three OPDx files for the stylus.

Manyu
--
Vimanyu Chadha
PhD Graduate Research Assistant
Department of Mechanical Engineering and Materials Science
Swanson School of Engineering
University of Pittsburgh
Jacobs Research Group
Email: ***@***.***
Phone: (217) 200 6398
--

**Comment by pastewka** [comment]
Hi @Vchadha2 - this looks to me like all the data is reliable. You are specifying a tip radius of 2 um. If I look at the scale-dependent curvature, then at smallest scales the curvature is around 10^-2 / um, which corresponds to an effective radius of 100 um. While I have to admit that this seems large, it is consistent with the fact that the whole region seem reliable. Are you sure the 2 um is correct?

**Comment by pastewka** [comment]
Hi @Vchadha2 can you confirm that this is the case?

**Comment by Vchadha2** [comment]
I talked to Tevis yesterday, we believe that the cutoff is still wrong and
are planning on to discuss it during the next roughness telecom.

Manyu

--
Vimanyu Chadha
PhD Graduate Research Assistant
Department of Mechanical Engineering and Materials Science
Swanson School of Engineering
University of Pittsburgh
Jacobs Research Group
Email: ***@***.***
Phone: (217) 200 6398
--

**Comment by mcrot** [comment]
Has this been discussed? Shall we plan a fix in a soon-to-be release?

**Comment by Vchadha2** [comment]
Talking to Tevis today in a couple of hours, will discuss and get back to
you guys.
Thanks,
Manyu
--
Vimanyu Chadha (he/him/his)
PhD Graduate Research Assistant
Department of Mechanical Engineering and Materials Science
Swanson School of Engineering
University of Pittsburgh
Jacobs Research Group
Email: ***@***.***
Phone: (217) 200 6398
--

**Comment by pastewka** [comment]
Not sure this is still an issue. Will reopen if it comes up again.
