### ISSUE TITLE
Reliability analysis

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#83]
See [current contact app](http://tribo.iam-cms.kit.edu/contactapp/) as reference.

The current app has three plots here: *1D*, *2D radial*, *2D map*

Is this needed in topobank in a similar way?

**Comment by pastewka** [comment]
From current discussion:

I think it would be better to have a generic field `Type of instrument` that has the options `Scanning probe`, `Optical` and `other`. If `Scanning Probe` is selection, a check box and a text field will open. The checkbox says `I know my tip radius`, such that the tip radius can be specified.

@tdbjacobs What do you think. Are these categories useful or do we need a finer graine specification of the instrument?

**Comment by tdbjacobs** [comment]
I agree - except that the term "scanning probe" is taken and tends to mean
specifically AFM. We could make this more generic by using terms like
"Contact" or "Tip-based"

Tevis Jacobs
William Kepler Whiteford Faculty Fellow and Associate Professor
Mechanical Engineering and Materials Science
University of Pittsburgh
http://www.engineering.pitt.edu/JacobsLab/
Mail: 636 Benedum Hall, 3700 O'Hara St., Pittsburgh, PA 15261
Office: 538-E Benedum Hall, 412-624-9736
tjacobs@pitt.edu

**Comment by pastewka** [comment]
From today's discussion:

* Each scale-dependent analysis function should return the reliable and the unreliable part of the analysis as separate data series
* Each data series can be set to show or hide by default and to be included in the averaging procedure

This way we can hide the unreliable part of the analysis and exclude it from the averaging procedure.

**Comment by pastewka** [comment]
The reliability analysis is relevant for:
* Power Spectrum
* Autocorrelation
* Scale-dependent Slope
* Variable Bandwidth
