### ISSUE TITLE
Profile imported incorrectly

### ISSUE THREAD

**Issue by Cora-Brown** [ContactEngineering/TopoBank#831]
I uploaded some profiles with a lot of overhangs and they are being uploaded incorrectly:
https://contact.engineering/manager/surface/1393/

**Comment by pastewka** [comment]
Oops, thanks for reporting this, I'll check what is going on.

**Comment by mcrot** [comment]
@pastewka, should we check it before the new release?

**Comment by pastewka** [comment]
Hi @Cora-Brown - sorry this has taken so long. However, it looks like the display is correct - this is your data file. It actually has those entries with negative heights etc. I am closing this as a non-issue.
