### ISSUE TITLE
User reported difficulty finding averaged PSD

### ISSUE THREAD

**Issue by tdbjacobs** [ContactEngineering/topobank#843]
<I tried to post this earlier, but had internet problems and I think it got lost. Sorry if this issue posts twice>

A user reported trouble finding the averaged PSD. I repeated his workflow and think I understand what happened. He was confused due to two issues:

(1) The average PSD is at the end, after all the topographies. For a big file, this is a lot of scrolling. 

**_Please change the order, putting the averaged PSD first, and individual topographies after._** 
(Most users will care most about the averaged PSD).

(2) The averaged PSD is called "Surface: <surface name>" - which may be confusing because we no longer use the term "Surface" and because it doesn't say anything about averagoing. To fix this:

**_Please change the title of the averaged data
FROM: "Surface: <surface name>"
TO: "Digital Surface Twin: <surface name>; Average of all individual PSDs"_**

Thanks,

Tevis

**Comment by pastewka** [comment]
Can you clarify: Does this apply to the current version? We just posted a big update that addressed issues like this.

**Comment by tdbjacobs** [comment]
Just confirmed it today.

NOTE: it is with the downloaded TXT file, not with the visualization

NOTE 2: I bet this same issue applies to ACF and other report-outs.

-Tevis

**Comment by pastewka** [comment]
Okay, we will look into this.

**Comment by pastewka** [comment]
@Siddhantsaka - Download function can be found here

https://github.com/ContactEngineering/topobank/blob/4e9ca2e909ed0dee34b7d3014e1fc6899721afde/topobank/analysis/downloads.py#L281

**Comment by Siddhantsaka** [comment]
Closed with https://github.com/ContactEngineering/topobank/pull/1005
