### ISSUE TITLE
Clarify authentication mechanism

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/TopoBank#851]
Right now, essentially every route has a check for permission which is an SQL request (I believe). Can this be made more efficient? Also, I don't understand how authentication works behind the scenes and how it would interact with a REST API.

**Comment by mcrot** [comment]
Hm - before we optimize the permission checking we should clarify whether it's a bottleneck. Somehow we have to know how the permissions are in that moment, a user can change permissions of a surface at any time.
Regarding authentication, the docs of Django Rest API has a related chapter: https://www.django-rest-framework.org/api-guide/authentication/
