### ISSUE TITLE
Point to github organization / repository more explicitely, for example on welcome page

### ISSUE THREAD

**Issue by sannant** [ContactEngineering/TopoBank#852]
I tell people that they will find our backend code if they go to contact.engineering. 

But I think it is hidden in info-version information. 

Would be nice to have a more explicit link, also to point out that we are open-source.

**Comment by pastewka** [comment]
To be frank, I don't see the point of being more explicit about where the source is. Only 1% of users will be interested in this and they will find it in the version information tab. I'm closing this issue.

**Comment by sannant** [comment]
I think it is easier to point someone that wants to use our backend code to the contact.engineering page. That was the reason. 
But what we should definititely do is to point to the paper. 

In the paper, we point to the backend, and anyone that wants to reasonably use the backend needs to read the paper before anyway.

**Comment by pastewka** [comment]
I agree - we absolutely need a pointer to the paper
