### ISSUE TITLE
OPDx files 

### ISSUE THREAD

**Issue by Vchadha2** [ContactEngineering/TopoBank#854]
OPDx files from the stylus cannot be calculated in PSD and it's showing as pending in status.
Let me know if I am doing something wrong?

https://contact.engineering/analysis/surface/1304/

**Comment by pastewka** [comment]
I think this may be a problem with the worker machine.

@mcrot can you check what is going on. I've had other problems with a bwCloud machine, I hope it is still up.

**Comment by mcrot** [comment]
I think there was a restart of the analysis machine and a temporary directory was missing.
As a workaround I've added a crontab entry to create the directory on every boot.
@Vchadha2 , could you check whether it's now working for you?

**Comment by Vchadha2** [comment]
I just checked, it's working now! 
Thank you!

**Comment by pastewka** [comment]
Perfect, thank you!
