### ISSUE TITLE
"Open" button seems to be not intuitive

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank#857]
Currently, when on the overview page for the analyses (where you select the functions),
each card has a button "Open". Pressing the button maximizes the analysis card and in 
case of "Contact mechanics" additionally some more functionality becomes accessible:

- Details on selected points from the contact plot, like a map of Contact pressure
- Widgets for changing parameters and triggering a new calculation

Recent feedback shows that this "Open" does not attract enough attention such that users try it.
We should think of another name, a new icon, colors...

**Comment by pastewka** [comment]
Closed by #965
