### ISSUE TITLE
Incorrect understanding/bug displaying analysis results? 

### ISSUE THREAD

**Issue by sitangshugk95** [ContactEngineering/TopoBank#859]
My focus is on the study of evolution of the contact geometry and gap of a randomly rough surface as a function of the applied pressure, and I have some weird results that I don't understand. I am a new user, so I might be wrong in my understanding - feel free to correct me.

The fractional contact area (A/A0) shows an expected trend - increasing with increasing pressure. If my understanding is correct, one would expect the contact patches (white regions) to increase and gaps (bright green regions) to reduce, as the fractional contact area increases. However, the contact geometry and gaps do not show this in the result image on the right-hand side when I click on the individual data points, as you can see in the image attached (the five images are corresponding to the first five datapoints, in order, left to right). 
![image (1)](https://user-images.githubusercontent.com/108830413/178683976-42fd368b-376b-4e6d-91df-54036187ab7f.png)

N.B. The scale bar is same in all the images, so it is not rescaling to a smaller range, and I have also changed the max # of iterations to 500, in case it is a convergence issue.

Is there something wrong in my fundamental understanding, or is this a bug where the images being shown are different from the data points being clicked on?

**Comment by mcrot** [comment]
Thanks @sitangshugk95, for opening this issue! As @pastewka mentioned by mail, this is a bug, the order of images seems to be wrong here. We'll fix that.
