### ISSUE TITLE
Harmonize JSON key name convention

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/topobank#870]
Right now, we are using underscores in Python and camelCase in JS, as per standard for these languages.

Naming of keys in JSON dictionary is currently mixed. Since those are mainly exposed to the JS side, my suggestion it to harmonize thus to camelCase.

Note: This will require rerunning all analyses to regenerate the JSON files.

@mcrot - any thought on this?

**Comment by mcrot** [comment]
I had rather kept the underscore syntax of Python everywhere in JSON, because I find it more readable and it underlines that it's the same thing. For me it feels needlessly complicated to change the syntax in the data because we cross a language barrier.

**Comment by mcrot** [comment]
Let's discuss that in person. Maybe I overlook where these names are used in JS and create an inconsistent sight of the code.

**Comment by pastewka** [comment]
It may not be possible to this, as analysis results are JSONs that are stored in the S3. Renaming things would mean recalculating all analyses. We are past the point where this is feasible.

**Comment by pastewka** [comment]
That said, we could automatically mangle snake_case into camelCase when reading JSONs. I'll keep this issue open, but I am unsure if it is worth the effort.

**Comment by pastewka** [comment]
Part of the code is now using camelCase. However, others (for example Bokeh and legacy JSON file) use snake_case. I am not sure we can resolve this issue. We should try to stay truer to the standard coding conventions on either side, but completely resolving These issues will not be possible.
