### ISSUE TITLE
Datepicker in measurement form does not work

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#879]
This is related to #878. The form's JS is needed, but when inserted, the layout is broken.

**Comment by mcrot** [comment]
This issue is true for the current system in production, but seems to be no longer an issue with the current develop branch.
I'm about to release it as new version 0.92.1. @21121995 , before you dig more deeply into this, please try the current develop branch or wait if this is still a problem when the new release is in production.

**Comment by mcrot** [comment]
After installing the new version 0.92.0, the datepicker actually works. It does not appear when clicking on the date itself,
but I think that's okay for now. Closing.

**Comment by 21121995** [comment]
okay
