### ISSUE TITLE
Remove docker compose file `production.yaml`

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#882]
We have one file for docker swarm for a while: `production-swarm.yaml`.
Still having the old file sometimes generates confusion and is error-prone, e.g.
containers are started which are not used any more.

**Comment by mcrot** [comment]
Also needs to be removed from several other files, e.g. ansible playbook.

**Comment by pastewka** [comment]
Agreed, remove

Michael Röttger ***@***.***> schrieb am Fr., 14. Okt. 2022,
17:56:
