### ISSUE TITLE
Analysis of multiple surfaces is failing

### ISSUE THREAD

**Issue by tdbjacobs** [ContactEngineering/topobank#897]
When I try to analyze multiple surfaces, the web app acts like it's working (i.e. the "please wait" message shows up). But, when it completes, no graphs are displayed. See screenshot. 

(My student confirmed that this happens for her as well.)

(As a potential clue, some of the measurements in these data sets have identical file names. It's possible that this is causing the problem, because when I try with other surfaces, I don't have the same issue.)

<img width="1877" alt="Screen Shot 2022-09-19 at 4 01 39 PM" src="https://user-images.githubusercontent.com/22891610/191106829-ad408345-f2c1-4d48-9b8f-f8ec6717fc86.png">

**Comment by mcrot** [comment]
Could you share these surfaces with me? That's easier for me to see what's going on.

**Comment by pastewka** [comment]
Closed by #965
