### ISSUE TITLE
Output format for PSD data is difficult to use

### ISSUE THREAD

**Issue by tdbjacobs** [ContactEngineering/topobank#909]
Problem 2: PSD output: Currently when we export the PSD of a DST with multiple measurements, it comes out with the average data in one sheet and each measurement in an additional sheet. However, multiple sheets are quite tedious to work with when you are writing to code to extract data. 
•       Discussion: Who is the Excel output for? 
•       Is it for the average engineer who wants to plot things in Excel? 
•       Or is it for the grad-student who wants to extract things for program? 
•       Consensus: We need to think more about how to solve this last problem. 
•       Python for windows: Antoine showed read_container routine in python that extracts data from zip file. 
•       We look forward to having this available.

**Comment by pastewka** [comment]
I'll be implementing this soon. Can you say what you want the sheets to look like? Do you simply want everything in a single sheet?

This is doable, but I don't fully understand why this is easier when processing the XLSX automatically. You would have:
* Many columns
* Each data set would have two columns as the wavevectors differ between datasets
* The length of each dataset differs, such that there would be a single table with columns that have different amounts of data.

Is this what you want @tdbjacobs @Vchadha2

**Comment by pastewka** [comment]
As a follow up, do you want all data series in a single sheet?

It would be good to get a mockup from you on what the XLSX should look like.

**Comment by pastewka** [comment]
Also tagging @ArushiPradhan here
