### ISSUE TITLE
Can't see my alerts

### ISSUE THREAD

**Issue by tdbjacobs** [ContactEngineering/topobank#912]
I can see that I have 33 alerts, but I can't see any but the top five newest. 
(I can't seem to scroll in the drop-down, nor can I find a link to see all alerts.) 

(Running Mac OS 12.4 > Chrome Version 106.0.5249.119 (Official Build) (arm64))

<img width="1475" alt="Screen Shot 2022-10-26 at 4 45 19 PM" src="https://user-images.githubusercontent.com/22891610/198134492-c7dbb5d6-e6b3-4e14-a13a-a987a8443ad5.png">

**Comment by mcrot** [comment]
Yes, the implementation is quite rudimentary. Issue #369 is related.
If you click on the first ones, the others will come up.  
If these messages are helpful, I agree we should not only improve the layout but also make all notifications available.

**Comment by mcrot** [comment]
Okay, now I see that you can't see the 5 *newest* - that should be possible, this is a bug.
