### ISSUE TITLE
Meaningful name suggestions for surface container download

### ISSUE THREAD

**Issue by jotelha** [ContactEngineering/topobank#961]
Currently, any download is named `digital_surface_twin.zip` per default. Would be nice to have a surface container named `APOL Roasted Chestnut Polished` actually suggested as something like `apol_roasted_chestnut_polished.zip` when downloaded.

**Comment by pastewka** [comment]
We can use `slugify` from Django to turn a string (name of a DST?) into something that can be used as a file name: https://docs.djangoproject.com/en/4.2/ref/utils/#django.utils.text.slugify

**Comment by Siddhantsaka** [comment]
If multiple surfaces are downloaded from different containers how should the default download name for the zip file be addressed?

**Comment by pastewka** [comment]
My suggestion is to pick an automatic name only if this is easily possible, i.e. if the user selected only a single `Surface` or `Topography` that both have names. It looks to me like the name selection needs to happen here:

https://github.com/ContactEngineering/topobank/blob/150aeba043a34981e76690368b7080313ecdbd9e/topobank/manager/views.py#L1649

This function gets a single `surface_id` which can be turned into a name using slugify, see here for the function signature:

https://github.com/ContactEngineering/topobank/blob/150aeba043a34981e76690368b7080313ecdbd9e/topobank/manager/views.py#L1607

It is a bit more difficult when the user decides to download an arbitrary selection, but that is this function:

https://github.com/ContactEngineering/topobank/blob/150aeba043a34981e76690368b7080313ecdbd9e/topobank/manager/views.py#L1677

My suggestion is to keep the generic name `digital_surface_twin.zip` if there are multiple surfaces that are selected, but pick the name of the surface if only one is selected. This should easy to check from the length of this list:

https://github.com/ContactEngineering/topobank/blob/150aeba043a34981e76690368b7080313ecdbd9e/topobank/manager/views.py#LL1685C5-L1685C13

@Siddhantsaka - let me know if you have questions about this.

**Comment by pastewka** [comment]
Closed with #994
