### ISSUE TITLE
Instrument’s native file format is not supported

### ISSUE THREAD

**Issue by jit15soni** [ContactEngineering/topobank#966]
Hi

Here I am raising an issue with raw data files uploading. I am trying to add raw files of roughness measurements to the digital surface twin collected using AFM, but the data files are of ".nid" format, which is not supported here. I am unable to upload any raw files. 

Thanks

**Comment by pastewka** [comment]
Can you provide a .nid file (by email to me?), I will then try to implement an import filter. If you have any documentation on that format, that would be great to. Ideally the file contains no sensitive data - please let me know if that is the case and whether I have permission to add the file to the SurfaceTopography repository where it would serve to test functionality of the code.

**Comment by jit15soni** [comment]
Thanks for your response. I will shortly share some .nid files with you. I am afraid I don't have any documentation for this format, but this file can be easily opened using Notepad. I can share the files of the same format, which are not related to the surface-topography challenge but can be used to resolve the issue.

**Comment by pastewka** [comment]
@jit15soni I've just released an update to the contact.engineering site, that implements NID/EZD file format support. Can you check whether your files work now? If not - let me know,  I'll fix asap.

**Comment by jit15soni** [comment]
Hi @pastewka 

Thanks again for your efforts. I checked, and I see that now I can upload the raw files on the contact.engineering website. I would like to add here that I tried uploading a few files, and analyzed the roughness measurements, and compared them with those obtained using Gywddion software. For some files, the roughness data obtained from the website matched quite well with those obtained using the software, whereas they varied significantly for others. For example, in one file, the roughness value determined using the software and website are 2.862 nm and 4.7995 nm, respectively. Below is the comparison of the topographies of the same file obtained using the website and software.

![Screenshot 2023-04-13 144125_improper line correction](https://user-images.githubusercontent.com/125862502/231737418-030fd57d-a0b1-41d0-bb2c-652a81c38ea5.jpg)

I guess that the significant difference between the roughness values of the same file is due to the inappropriate processing of the topography by the website (as can be observed in the above image), despite setting the detrend mode as "remove curvature and tilt". I am reporting a few topographies obtained from the website along with their roughness value and comparing them with those obtained using the Gwyddion software below.

![Screenshot 2023-04-13 175112_topographies and roughness comparison](https://user-images.githubusercontent.com/125862502/231756694-dde2ab9d-a0a7-4da5-ad21-9036b406877f.jpg)

**Comment by jit15soni** [comment]
Hi Prof. @pastewka,

I've shared the files with you via email to [lars.pastewka@imtek.uni-freiburg.de](mailto:lars.pastewka@imtek.uni-freiburg.de)

**Comment by jit15soni** [comment]
Hi Prof. @pastewka 

I hope you are well. I would like to make a kind inquiry regarding the status of this issue. I would appreciate some feedback as the deadline (31st August 2023) is approaching closer in a couple of months. This may be helpful to decide if I need to take new measurements, provided there is any issue with the raw file.

Thanks

**Comment by pastewka** [comment]
Hi @jit15soni - sorry, I simply forgot to communicate back. I don't think there is an issue with the system. I think you are comparing different data channels. You can select the data channel right after uploading.
