### ISSUE TITLE
web app is really slow and not loading

### ISSUE THREAD

**Issue by Cyrian-24** [ContactEngineering/topobank#967]
Waited for 15 minutes and teh website is not loading or computing measurements, thank you!

**Comment by pastewka** [comment]
The web app seems to lock up at certain times. It then takes it 1-2 minutes to recover. I think what is happening is that DJango can handle only a finite number of requests. If *all* of these requests take a long time, then the system locks up until the first finished. At this point, I have no idea what is causing requests to take a long time. My best guess is checking Celery task statuses, i.e. a problem with the message queue.

**Comment by pastewka** [comment]
I think the culprit is the `request_analysis`, as this problem appear to occur when many new analyses are requested.

**Comment by pastewka** [comment]
Hi @Cyrian-24 - we pushed a couple of performance tweaks. Can you give us feedback if the site feels faster now?

**Comment by pastewka** [comment]
Should be partially resolved with #1012 - need to observe what will happen but closing this for now.
