### ISSUE TITLE
PSD image not loading

### ISSUE THREAD

**Issue by ArushiPradhan** [ContactEngineering/topobank#987]
Hello,
The PSD task list shows success but there is no PSD image that is loaded. The success or pending bars that normally show up before the PSD loading also does not show. Here are screenshots:
![image](https://github.com/ContactEngineering/topobank/assets/78487900/3307b365-9363-4eca-b584-523e0dc7e067)
![image](https://github.com/ContactEngineering/topobank/assets/78487900/b49680e1-51d3-46fb-b504-b140ac866efa)

This has happened multiple times now.
Thank you,
Arushi

**Comment by ArushiPradhan** [comment]
![image](https://github.com/ContactEngineering/topobank/assets/78487900/3a42ea16-a4b1-4beb-a68a-d394fc90e0cd)

**Comment by pastewka** [comment]
This may have been fixed with #965. I am closing this, please reopen when issue persists @ArushiPradhan
