### ISSUE TITLE
AFM file (.spm) is being read incorrectly

### ISSUE THREAD

**Issue by ArushiPradhan** [ContactEngineering/topobank#988]
I am trying to upload a rectangular AFM measurement with dimensions 1000nm in y and 500 nm in x, but the web app is uploading a square with same x and y.
here are images:
![image](https://github.com/ContactEngineering/topobank/assets/78487900/2064fcad-76ca-41da-9268-8e64c02b6787)
![image](https://github.com/ContactEngineering/topobank/assets/78487900/2e806091-4130-4df3-9e55-5c4eafd5e1f5)

This is what it should look like (from the nanoscope Analysis software):
![image](https://github.com/ContactEngineering/topobank/assets/78487900/68752552-36ea-40a2-8607-2a1ec9c036c3)

**Comment by pastewka** [comment]
Related to #764

**Comment by pastewka** [comment]
Hi @ArushiPradhan - can you check if the current version still reports the wrong physical size? The rendering will be square. This is a limitation of the code displaying the zoomable image. We are working on resolving this.

**Comment by ArushiPradhan** [comment]
Hi Dr. Pastewka,
I no longer have this file to test it, sorry!

Thank you,
 Arushi
________________________________
